// One-shot generator: 200 Top-10 AI Tools 2027 intent keyword phrases.
const fs = require('fs');
const PHRASES = [
  // Transactional (1-20)
  'Best AI Tools for 2027',
  'Buy AI software subscriptions 2027',
  'AI tool pricing comparison 2027',
  'Affordable AI tools for small business',
  'Enterprise AI platform pricing 2027',
  'Free AI tools trial no credit card',
  'Best AI tool deals and discounts 2027',
  'AI SaaS subscription value ranking',
  'Pay-as-you-go AI API tools 2027',
  'Best paid AI tools worth the money',
  'Cheapest professional AI tools 2027',
  'AI tools monthly subscription under $20',
  'Team AI workspace pricing comparison',
  'AI tool bundle deals for startups',
  'Corporate AI tool procurement list',
  'AI tool license comparison enterprise',
  'Best AI tools for bootstrapped founders',
  'AI software buying guide 2027',
  'Where to buy AI tool subscriptions',
  'Best value AI tools for freelancers',
  // Informational (21-40)
  'What are the top AI tools in 2027',
  'How to choose AI tools for your workflow',
  'AI tools explained for beginners 2027',
  'What AI tools do professionals use',
  'Guide to AI tool categories 2027',
  'How AI tools work for content creation',
  'AI tool features comparison guide',
  'Understanding AI tool APIs in 2027',
  'AI tools glossary and definitions',
  'How to evaluate AI tool quality',
  'What makes a good AI tool in 2027',
  'AI tool integration basics explained',
  'How to stack AI tools together',
  'AI tool security and privacy guide',
  'AI tool data training opt-out guide',
  'How to onboard teams on AI tools',
  'AI tool workflow automation explained',
  'What is agentic AI software 2027',
  'How to read AI tool benchmarks',
  'When to switch AI tools in 2027',
  // Category-specific (41-70)
  'Top 10 AI tools for writing in 2027',
  'Top 10 AI tools for coding in 2027',
  'Top 10 AI tools for video editing in 2027',
  'Top 10 AI tools for image generation in 2027',
  'Top 10 AI tools for voice cloning in 2027',
  'Top 10 AI tools for music creation in 2027',
  'Top 10 AI tools for graphic design in 2027',
  'Top 10 AI tools for marketing in 2027',
  'Top 10 AI tools for SEO in 2027',
  'Top 10 AI tools for email writing in 2027',
  'Top 10 AI tools for resume building in 2027',
  'Top 10 AI tools for presentation slides in 2027',
  'Top 10 AI tools for transcription in 2027',
  'Top 10 AI tools for data analysis in 2027',
  'Top 10 AI tools for chatbots in 2027',
  'Top 10 AI tools for animation in 2027',
  'Top 10 AI tools for logo design in 2027',
  'Top 10 AI tools for social media in 2027',
  'Top 10 AI tools for customer support in 2027',
  'Top 10 AI tools for research in 2027',
  'Top 10 AI tools for meeting notes in 2027',
  'Top 10 AI tools for spreadsheet automation in 2027',
  'Top 10 AI tools for PDF summarization in 2027',
  'Top 10 AI tools for website building in 2027',
  'Top 10 AI tools for app development in 2027',
  'Top 10 AI tools for 3D modeling in 2027',
  'Top 10 AI tools for photo editing in 2027',
  'Top 10 AI tools for podcast production in 2027',
  'Top 10 AI tools for legal document review in 2027',
  'Top 10 AI tools for sales outreach in 2027',
  // Problem/solution (71-90)
  'AI tools to fix writer block 2027',
  'AI tools to speed up coding workflows',
  'AI tools to reduce video editing time',
  'AI tools to automate repetitive tasks',
  'AI tools to improve content quality',
  'AI tools to replace manual data entry',
  'AI tools to scale customer support',
  'AI tools to generate marketing copy fast',
  'AI tools to fix poor meeting productivity',
  'AI tools to reduce design costs',
  'AI tools to improve SEO rankings',
  'AI tools to transcribe meetings accurately',
  'AI tools to build prototypes faster',
  'AI tools to personalize email at scale',
  'AI tools to summarize long documents',
  'AI tools to create social posts quickly',
  'AI tools to debug code faster',
  'AI tools to remove background from images',
  'AI tools to clone voice for podcasts',
  'AI tools to automate slide deck creation',
  // Qualitative (91-110)
  'Best overall AI tools 2027',
  'Highest rated AI tools 2027',
  'Most popular AI tools right now',
  'Fastest AI tools for productivity',
  'Most accurate AI writing tools',
  'Best free AI tools 2027',
  'Best open source AI tools 2027',
  'Most user-friendly AI tools',
  'Best AI tools for power users',
  'Most reliable AI tools for business',
  'Best AI tools with free tiers',
  'Top rated AI image generators 2027',
  'Best AI coding assistants 2027',
  'Most creative AI tools 2027',
  'Best AI tools for quality output',
  'Top AI tools for speed and latency',
  'Best AI tools for privacy conscious users',
  'Most versatile AI tools 2027',
  'Best AI tools for daily use',
  'Top AI tools experts recommend 2027',
  // Comparison (111-130)
  'ChatGPT vs Claude AI tools 2027',
  'Midjourney vs DALL-E comparison 2027',
  'GitHub Copilot vs Cursor comparison',
  'Jasper vs Copy.ai for marketing',
  'Notion AI vs Microsoft Copilot',
  'Runway vs Pika for AI video',
  'ElevenLabs vs Murf voice AI',
  'Perplexity vs ChatGPT for research',
  'Canva AI vs Adobe Firefly',
  'Zapier AI vs Make automation tools',
  'Otter vs Fireflies meeting AI',
  'Grammarly vs ProWritingAid AI',
  'Synthesia vs HeyGen avatar video',
  'Replit vs Codeium for coding',
  'Descript vs CapCut AI editing',
  'Best ChatGPT alternatives 2027',
  'Best Claude alternatives for teams',
  'OpenAI vs Google Gemini tools',
  'Free vs paid AI tools comparison',
  'AI tool benchmark leaderboard 2027',
  // Audience (131-150)
  'Best AI tools for students 2027',
  'Best AI tools for developers 2027',
  'Best AI tools for marketers 2027',
  'Best AI tools for designers 2027',
  'Best AI tools for entrepreneurs',
  'Best AI tools for content creators',
  'Best AI tools for remote teams',
  'Best AI tools for solopreneurs',
  'Best AI tools for enterprise teams',
  'Best AI tools for nonprofits 2027',
  'Best AI tools for teachers and educators',
  'Best AI tools for lawyers and legal teams',
  'Best AI tools for healthcare professionals',
  'Best AI tools for real estate agents',
  'Best AI tools for ecommerce sellers',
  'Best AI tools for HR and recruiting',
  'Best AI tools for finance analysts',
  'Best AI tools for journalists',
  'Best AI tools for podcasters 2027',
  'Best AI tools for YouTubers 2027',
  // Emerging (151-170)
  'Agentic AI tools for automation 2027',
  'Multimodal AI tools to watch 2027',
  'AI tools with computer use agents',
  'Next generation AI coding agents 2027',
  'AI tools with real-time web access',
  'On-device AI tools for privacy 2027',
  'AI tools for local LLM deployment',
  'Future of AI productivity tools 2027',
  'AI tools integrating MCP protocols',
  'AI tools with custom model fine-tuning',
  'AI tools for autonomous workflows',
  'Emerging AI video generation tools 2027',
  'AI tools for scientific research 2027',
  'AI tools for robotics and hardware',
  'AI tools for edge computing 2027',
  'AI tools with voice-first interfaces',
  'AI tools for AR and VR content',
  'AI tools for synthetic data generation',
  'AI tools for compliance automation',
  'New AI tool launches to try 2027',
  // Misc long-tail (171-199)
  'AI tools list for beginners 2027',
  'Complete AI tools stack for startups',
  'AI tools every office should use',
  'AI tools for side hustle income',
  'AI tools for agency client work',
  'AI tools for B2B SaaS teams',
  'AI tools for product managers 2027',
  'AI tools for UX researchers',
  'AI tools for DevOps engineers',
  'AI tools for customer success teams',
  'AI tools for RevOps automation',
  'AI tools for sales enablement 2027',
  'AI tools for competitive intelligence',
  'AI tools for knowledge management',
  'AI tools for internal documentation',
  'AI tools for multilingual content',
  'AI tools for accessibility features',
  'AI tools for brand consistency',
  'AI tools for A/B test copy variants',
  'AI tools for landing page optimization',
  'AI tools for influencer marketing',
  'AI tools for ad creative generation',
  'AI tools for CRM enrichment',
  'AI tools for webinar production',
  'AI tools for event planning 2027',
  'AI tools for inventory forecasting',
  'AI tools for contract drafting',
  'AI tools for grant writing',
  'AI tools roundup newsletter picks 2027',
  // Anchor close (200)
  'The Ultimate List: Top 10 AI Tools 2027',
];
if (PHRASES.length !== 200) {
  console.error('Expected 200 phrases, got', PHRASES.length);
  process.exit(1);
}
fs.writeFileSync(
  'C:/Users/koryj/website/_ai_keyword_phrases.json',
  JSON.stringify(PHRASES, null, 2) + '\n'
);
console.log('wrote', PHRASES.length, 'phrases');
