#!/usr/bin/env node
// Generate _bo_keyword_phrases.json — 200 commercial buildout / TI / fit-out SEO phrases.
const fs = require('fs');
const phrases = [
  // Core definitions & intent (1–20)
  'What is a commercial buildout',
  'What is a tenant improvement allowance',
  'What is a commercial fit-out',
  'What is TI in commercial real estate',
  'What is a leasehold improvement',
  'What is a warm shell delivery condition',
  'What is a turnkey commercial buildout',
  'What is build-to-suit commercial construction',
  'What is a white box commercial space',
  'What is a grey shell vs warm shell',
  'What is a tenant improvement work letter',
  'What is a commercial buildout timeline',
  'What is a commercial construction draw schedule',
  'What is a commercial lease buildout clause',
  'What is a landlord work vs tenant work split',
  'What is a commercial space delivery condition',
  'What is a commercial buildout punch list',
  'What is a commercial occupancy permit timeline',
  'What is a commercial buildout contingency budget',
  'What is a commercial buildout scope of work',

  // Cost & budgeting (21–45)
  'Commercial buildout cost per square foot 2027',
  'Tenant improvement cost per square foot by industry',
  'How much does a restaurant buildout cost',
  'How much does a retail store buildout cost',
  'How much does a medical office buildout cost',
  'How much does a dental office buildout cost',
  'How much does an office buildout cost per SF',
  'How much does a warehouse buildout cost',
  'How much does a gym fitness studio buildout cost',
  'How much does a salon spa buildout cost',
  'How to budget a commercial buildout without overspending',
  'Commercial buildout hidden costs landlords do not disclose',
  'How to value-engineer a commercial buildout',
  'Commercial buildout contingency percentage rule of thumb',
  'How to phase a buildout to reduce upfront cash',
  'All-in commercial lease cost per square foot calculator',
  'Commercial buildout cost vs TI allowance gap',
  'How to estimate MEP costs in a commercial buildout',
  'Commercial buildout soft costs vs hard costs breakdown',
  'How change orders blow up buildout budgets',
  'How to cap change orders in a commercial buildout contract',
  'Commercial buildout cost escalation clauses',
  'How to compare three commercial buildout bids',
  'Commercial buildout allowance unused credit negotiation',
  'How much TI allowance should I ask for per square foot',

  // Lease negotiation & CRE (46–75)
  'How to negotiate a tenant improvement allowance',
  'Gross lease vs triple net lease for tenants',
  'How to negotiate CAM charges and caps',
  'How to negotiate free rent and rent abatement',
  'How to avoid getting screwed by your landlord on buildout',
  'Commercial lease red flags before signing',
  'How to negotiate a personal guarantee burn-off',
  'How to get out of a commercial lease early',
  'How to negotiate a kick-out clause for low sales',
  'What is percentage rent and how to negotiate it',
  'How to negotiate operating expense stops',
  'How to avoid paying for landlord capital improvements',
  'What is a relocation clause in a commercial lease',
  'What is a recapture clause and how to remove it',
  'What is an SNDA and why tenants need one',
  'What is an estoppel certificate trap',
  'How to negotiate signage rights in a lease',
  'How to get right of first refusal on adjacent space',
  'What is a go-dark clause in retail leases',
  'Should I use a tenant rep broker who pays',
  'How binding is a letter of intent for buildout',
  'Cash TI allowance vs landlord amortized TI',
  'How to structure buildout if the deal falls through',
  'How to get paid for buildout you leave behind',
  'How to negotiate landlord construction management fees',
  'How to cap landlord TI amortization interest',
  'How to negotiate security deposit reduction',
  'How to avoid double-paying property taxes NNN',
  'How to negotiate exclusivity in a shopping center lease',
  'How to negotiate co-tenancy clauses retail lease',

  // Construction process & contractors (76–95)
  'How to vet a general contractor for commercial buildout',
  'Commercial buildout permit timeline by city',
  'How to manage a commercial construction draw schedule',
  'Design-build vs design-bid-build commercial fit-out',
  'How to write a commercial buildout scope of work',
  'How to hire a commercial architect for tenant improvements',
  'How to coordinate MEP engineers on a buildout',
  'Commercial buildout inspection checklist before payment',
  'How to run a commercial buildout punch list walkthrough',
  'How to avoid lien claims on a tenant improvement',
  'Commercial buildout insurance requirements COI checklist',
  'How long does a commercial buildout take',
  'Fast-track commercial buildout strategies',
  'How to sequence demolition and buildout phases',
  'Commercial buildout ADA compliance requirements',
  'Commercial kitchen hood and grease trap requirements',
  'Commercial buildout fire code egress requirements',
  'How to get a certificate of occupancy faster',
  'Commercial buildout warranty and callback period',
  'How to hold retainage on a commercial GC contract',

  // Industry-specific buildouts (96–125)
  'Restaurant commercial kitchen buildout requirements',
  'Quick-service restaurant buildout cost guide',
  'Coffee shop cafe buildout budget checklist',
  'Bar nightclub buildout liquor license timing',
  'Retail boutique buildout fixture budget',
  'Grocery and convenience store buildout costs',
  'Medical clinic buildout HIPAA and infection control',
  'Dental operatory buildout plumbing requirements',
  'Veterinary clinic commercial buildout guide',
  'Pharmacy retail buildout compliance checklist',
  'Daycare childcare center buildout licensing',
  'Fitness gym studio buildout flooring and HVAC',
  'Yoga pilates studio buildout soundproofing',
  'Salon barbershop buildout plumbing stations',
  'Spa wellness center buildout wet room costs',
  'Hotel lobby renovation tenant improvement scope',
  'Auto repair shop buildout bay requirements',
  'Car wash commercial buildout utility upgrades',
  'Laundromat commercial buildout plumbing electrical',
  'Warehouse light industrial buildout racking HVAC',
  'Cold storage commercial buildout refrigeration costs',
  'Data center tenant improvement power cooling',
  'Office buildout open plan vs private offices cost',
  'Law firm office buildout conference room AV',
  'Coworking space buildout density and code',
  'Showroom commercial buildout lighting display',
  'Brewery taproom buildout zoning and drainage',
  'Church nonprofit community space buildout',
  'School tutoring center commercial buildout permits',
  'Pet grooming boarding facility buildout zoning',

  // Location — [City] / Maryland / Mid-Atlantic (126–140)
  'Commercial buildout cost per square foot in [City]',
  'Tenant improvement allowance norms in [City]',
  'How long commercial permits take in [City]',
  'Best commercial general contractors in [City]',
  'Retail lease TI rates in [City] 2027',
  'Restaurant buildout costs in Maryland',
  'Medical office buildout costs in Maryland',
  'Commercial buildout permitting in Mid-Atlantic states',
  'NNN lease vs gross lease norms in [City]',
  'Office vacancy and TI concessions in [City]',
  'Shopping center lease buildout rules in [City]',
  'Historic building commercial buildout restrictions [City]',
  'Commercial zoning change timeline in [City]',
  'Maryland commercial tenant improvement tax treatment',
  'Mid-Atlantic commercial construction labor rates 2027',

  // Comparative / vs (141–160)
  'Build-to-suit vs tenant-managed buildout',
  'Demolish old building vs build-to-suit decision',
  'Turnkey buildout vs TI allowance cash out',
  'Warm shell vs turnkey delivery cost comparison',
  'As-is vs warm shell vs turnkey which saves money',
  'Gross lease vs NNN which saves tenants money',
  'Buy building vs lease and buildout analysis',
  'SBA 504 loan vs conventional for owner-occupied buildout',
  'Sale-leaseback vs owning your commercial building',
  'Landlord GC vs tenant-hired contractor buildout',
  'Design-build vs traditional bid for fit-out speed',
  'Modular construction vs stick-built commercial buildout',
  'New construction vs second-generation space buildout',
  'Sublease vs original lease takeover buildout risk',
  'Franchise turnkey package vs independent buildout',
  'Ground lease vs building purchase for retail',
  'Single tenant vs multi-tenant CAM cost comparison',
  'Class A vs Class B office buildout cost delta',
  'Urban inline retail vs strip center buildout costs',
  'Owner-occupied vs investor CRE buildout incentives',

  // Financing & ownership (161–175)
  'How to finance a commercial tenant improvement',
  'SBA 7a vs SBA 504 for commercial buildout',
  'How to use TI allowance as effective rent discount',
  'Sale-leaseback pros cons for buildout recovery',
  'How to buy commercial building through an LLC',
  'Equipment financing vs buildout loan for tenant improvements',
  'How to amortize buildout costs for tax purposes',
  'Section 179 vs bonus depreciation leasehold improvements',
  'How to structure buildout loan with landlord contribution',
  'Working capital line for commercial buildout cash flow',
  'How to recover buildout investment at lease end',
  'Tenant improvement allowance accounting treatment',
  'How to negotiate unused TI credit at renewal',
  'Bridge loan timing for commercial buildout draws',
  'How landlords finance tenant improvement packages',

  // Future trends & sustainability (176–190)
  'Sustainable commercial buildout materials 2027',
  'Net-zero ready tenant improvement strategies',
  'Smart building sensors in commercial fit-outs',
  'Modular prefab commercial buildout trends',
  'Biophilic design in office tenant improvements',
  'EV charging station buildout for commercial landlords',
  'Post-pandemic office buildout hybrid layouts',
  'Touchless fixtures commercial restroom buildout',
  'LED lighting ROI in retail buildouts',
  'HVAC electrification commercial tenant improvements',
  'Well Building Standard commercial fit-out costs',
  'ESG reporting for commercial buildout projects',
  'Adaptive reuse commercial buildout tax credits',
  'Mass timber commercial interior buildout trends',
  'AI space planning tools for commercial buildouts',

  // Long-tail strategy & Pulse brand (191–200)
  'How not to get screwed on a commercial buildout lease',
  'Complete commercial lease negotiation checklist for tenants',
  'Commercial buildout mistakes that cost six figures',
  'How to negotiate every line of a work letter',
  'Tenant rep questions to ask before signing buildout lease',
  'Commercial buildout due diligence before LOI',
  'How to protect your TI deposit from landlord disputes',
  'Step-by-step commercial buildout from LOI to opening',
  'Pulse Buildouts commercial lease and TI guides',
  'The ultimate commercial buildout strategy',
];

if (phrases.length !== 200) {
  console.error('Expected 200 phrases, got', phrases.length);
  process.exit(1);
}
fs.writeFileSync(
  require('path').join(__dirname, '_bo_keyword_phrases.json'),
  JSON.stringify(phrases, null, 2) + '\n'
);
console.log('Wrote', phrases.length, 'phrases to _bo_keyword_phrases.json');
