// 300 NEW Coaching (cg####) topics → cg0201–cg0500. Distinct from the existing 200.
// Run: node _cg_topics_201_500.js   → writes _manifest_cg2.json (the 300 new topics)
// and validates zero normalized-title collisions against _manifest_cg.json.
const fs = require('fs');

const Q = [
  // ── A. By role / motion ──
  "How do you coach an SDR who books meetings that never show up?",
  "How do you coach a BDR to research accounts before reaching out?",
  "How do you coach an AE who inherited a messy pipeline?",
  "How do you coach an account manager to grow existing accounts?",
  "How do you coach a CSM to spot expansion opportunities?",
  "How do you coach a sales engineer to sell, not just demo?",
  "How do you coach a channel rep to manage partners, not end users?",
  "How do you coach an inside sales rep to sound consultative on the phone?",
  "How do you coach a field rep to use their time in-territory well?",
  "How do you coach an enterprise AE to navigate a buying committee?",
  "How do you coach an SMB rep to move fast without cutting corners?",
  "How do you coach a mid-market rep stepping up from SMB deals?",
  "How do you coach a full-cycle rep to balance prospecting and closing?",
  "How do you coach an overlay specialist who doesn't own the quota?",
  "How do you coach a renewals rep to protect revenue without discounting?",
  "How do you coach a rep moving from SMB to enterprise selling?",
  "How do you coach a hunter to handle account management duties?",
  "How do you coach a farmer rep to start hunting new logos?",
  "How do you coach a partner manager to drive sourced pipeline?",
  "How do you coach a solutions consultant to qualify deals earlier?",

  // ── B. Methodology adoption ──
  "How do you coach reps to actually use MEDDIC on every deal?",
  "How do you coach a rep to find the economic buyer in MEDDPICC?",
  "How do you coach reps to run a Challenger 'teach' moment?",
  "How do you coach reps to use SPIN questions in discovery?",
  "How do you coach reps on the Sandler up-front contract?",
  "How do you coach reps to deliver a Command of the Message pitch?",
  "How do you coach reps to sell on business value, not features?",
  "How do you coach reps to use GAP selling to create urgency?",
  "How do you coach reps to build a mutual action plan with buyers?",
  "How do you coach reps to qualify out bad deals faster?",
  "How do you coach reps to identify a champion versus a coach?",
  "How do you coach reps to map the full buying committee?",
  "How do you coach reps to quantify pain in dollars?",
  "How do you coach reps to tie discovery to metrics that matter?",
  "How do you coach reps to use the JOLT method on indecisive buyers?",

  // ── C. Discovery & qualification ──
  "How do you coach a rep to run a discovery call that earns a second meeting?",
  "How do you coach a rep who asks surface-level discovery questions?",
  "How do you coach a rep to uncover the buyer's compelling event?",
  "How do you coach a rep to slow down and listen on discovery calls?",
  "How do you coach a rep to ask better follow-up questions?",
  "How do you coach a rep to qualify budget without being awkward?",
  "How do you coach a rep to confirm decision process early?",
  "How do you coach a rep to disqualify a deal that won't close?",
  "How do you coach a rep who takes every buyer's word at face value?",
  "How do you coach a rep to dig into the cost of inaction?",
  "How do you coach a rep to surface hidden objections in discovery?",
  "How do you coach a rep to set a clear next step on every call?",

  // ── D. Demos & technical selling ──
  "How do you coach a rep to tailor a demo to the buyer's use case?",
  "How do you coach a rep who demos every feature instead of the relevant ones?",
  "How do you coach a rep to handle a technical objection mid-demo?",
  "How do you coach a rep to run a demo with a mixed technical and business audience?",
  "How do you coach a rep to set up a proof of concept that closes?",
  "How do you coach a rep to bring in a sales engineer at the right time?",
  "How do you coach a rep to turn a demo request into real discovery first?",
  "How do you coach a rep to handle a 'just send me a demo' request?",
  "How do you coach a rep to recap a demo so it moves the deal?",
  "How do you coach a rep to demo confidently when the product has gaps?",

  // ── E. Objection handling ──
  "How do you coach a rep to handle the 'you're too expensive' objection?",
  "How do you coach a rep to respond when a buyer says 'we use a competitor'?",
  "How do you coach a rep to handle 'we have no budget right now'?",
  "How do you coach a rep to respond to 'send me some information'?",
  "How do you coach a rep to handle 'we're happy with what we have'?",
  "How do you coach a rep to deal with 'call me back next quarter'?",
  "How do you coach a rep to handle 'I need to talk to my boss'?",
  "How do you coach a rep to respond to 'we're building this in-house'?",
  "How do you coach a rep to handle 'we tried something like this before'?",
  "How do you coach a rep to respond when a buyer goes silent?",
  "How do you coach a rep to handle objections without getting defensive?",
  "How do you coach a rep to surface the real objection behind the stall?",
  "How do you coach a rep to handle a security or compliance objection?",
  "How do you coach a rep to respond to 'your company is too small'?",

  // ── F. Negotiation, pricing, discounting ──
  "How do you coach a rep to hold price under pressure?",
  "How do you coach a rep who discounts at the first sign of resistance?",
  "How do you coach a rep to trade concessions instead of giving them away?",
  "How do you coach a rep to present pricing with confidence?",
  "How do you coach a rep to handle a procurement-led negotiation?",
  "How do you coach a rep to defend value when undercut by a competitor?",
  "How do you coach a rep to negotiate multi-year contracts?",
  "How do you coach a rep to avoid end-of-quarter discount panic?",
  "How do you coach a rep to walk away from a bad deal?",
  "How do you coach a rep to anchor pricing early in the deal?",
  "How do you coach a rep to handle a 'give me your best price' demand?",
  "How do you coach a rep to negotiate with a professional buyer?",
  "How do you coach a rep to sell value when the buyer only cares about price?",
  "How do you coach a rep to protect margin on renewals?",

  // ── G. Closing & urgency ──
  "How do you coach a rep who's afraid to ask for the sale?",
  "How do you coach a rep to create urgency without being pushy?",
  "How do you coach a rep to run an effective close plan?",
  "How do you coach a rep to handle a deal that keeps slipping?",
  "How do you coach a rep to get a verbal commitment before paperwork?",
  "How do you coach a rep to close a deal stuck in legal?",
  "How do you coach a rep to reach the signature step faster?",
  "How do you coach a rep to handle a last-minute new stakeholder?",
  "How do you coach a rep to ask for the close on the first call when it fits?",
  "How do you coach a rep to recover a deal that went dark at the finish line?",
  "How do you coach a rep to use a compelling event to drive a close date?",
  "How do you coach a rep to confirm the buyer's signing process early?",

  // ── H. Prospecting / outbound / cold calling / email / social ──
  "How do you coach a rep to write cold emails that get replies?",
  "How do you coach a rep to build a prospecting list that converts?",
  "How do you coach a rep to personalize outreach at scale?",
  "How do you coach a rep to leave voicemails that get callbacks?",
  "How do you coach a rep to open a cold call without getting hung up on?",
  "How do you coach a rep to use LinkedIn for social selling?",
  "How do you coach a rep to book meetings with senior executives?",
  "How do you coach a rep to follow up without being annoying?",
  "How do you coach a rep to handle a gatekeeper?",
  "How do you coach a rep to write a subject line that gets opened?",
  "How do you coach a rep to run a multichannel outbound sequence?",
  "How do you coach a rep to re-engage cold leads from last year?",
  "How do you coach a rep to ask for referrals from happy customers?",
  "How do you coach a rep to turn inbound leads into qualified meetings?",
  "How do you coach a rep to research a prospect in five minutes?",
  "How do you coach a rep to handle rejection on the phones?",
  "How do you coach a rep to hit their daily activity numbers?",
  "How do you coach a rep to book meetings at a trade show or event?",
  "How do you coach a rep to warm up an account before reaching out?",
  "How do you coach a rep to use a trigger event in their outreach?",

  // ── I. Pipeline / forecasting / CRM / deal management ──
  "How do you coach a rep to keep their CRM up to date?",
  "How do you coach a rep to forecast deals honestly?",
  "How do you coach a rep who sandbags their forecast?",
  "How do you coach a rep who has happy ears about every deal?",
  "How do you coach a rep to build enough pipeline to hit quota?",
  "How do you coach a rep to prioritize the deals most likely to close?",
  "How do you coach a rep to run a clean pipeline review?",
  "How do you coach a rep to set accurate close dates?",
  "How do you coach a rep to manage twenty deals at once?",
  "How do you coach a rep to advance every deal to a clear next step?",
  "How do you coach a rep to qualify deals out of the forecast?",
  "How do you coach a rep to read buying signals in the data?",
  "How do you coach a rep to use deal stages consistently?",
  "How do you coach a rep to spot a deal that's actually dead?",
  "How do you coach a rep to log call notes that are actually useful?",

  // ── J. Specific rep behaviors / problems ──
  "How do you coach a rep who talks too much on sales calls?",
  "How do you coach a rep who single-threads every deal?",
  "How do you coach a rep who won't follow the sales process?",
  "How do you coach a rep who blames marketing for bad leads?",
  "How do you coach a rep who's great in person but weak on video calls?",
  "How do you coach a rep who chases small, easy deals?",
  "How do you coach a rep who's inconsistent month to month?",
  "How do you coach a rep who resists every piece of feedback?",
  "How do you coach a rep who's smart but lazy on activity?",
  "How do you coach a rep who's a hard worker but low on skill?",
  "How do you coach a rep who oversells and creates churn?",
  "How do you coach a rep who won't ask for the next meeting?",
  "How do you coach a rep who gets nervous talking to executives?",
  "How do you coach a rep who builds great rapport but no urgency?",
  "How do you coach a rep who skips qualification to chase the demo?",
  "How do you coach a rep who avoids the phone and hides in email?",
  "How do you coach a rep who's defensive in pipeline reviews?",
  "How do you coach a rep who never asks for help until it's too late?",
  "How do you coach a rep who's coasting after a big year?",
  "How do you coach a rep whose deals always slip to next quarter?",
  "How do you coach a rep who can't tell a good deal from a bad one?",
  "How do you coach a rep who relies only on inbound leads?",
  "How do you coach a rep who's afraid to talk about money?",
  "How do you coach a rep who agrees in the 1:1 but never changes?",
  "How do you coach a rep who's technically strong but can't build rapport?",
  "How do you coach a rep who lets buyers control the whole process?",
  "How do you coach a rep who won't multithread into the C-suite?",
  "How do you coach a rep who gives up after one 'no'?",
  "How do you coach a rep who over-promises to close the deal?",
  "How do you coach a rep who's disorganized and misses follow-ups?",

  // ── K. Onboarding / ramp / 30-60-90 ──
  "How do you coach a new sales hire through their first week?",
  "How do you coach a new rep to their first closed deal?",
  "How do you build a 30-60-90 ramp plan for a new AE?",
  "How do you coach a new rep on your product's competitive landscape?",
  "How do you coach a new rep to learn the buyer's industry fast?",
  "How do you coach an experienced hire who's used to a different process?",
  "How do you coach a new rep to shadow calls effectively?",
  "How do you know if a new rep is going to make it?",
  "How do you coach a new rep who's ramping slower than expected?",
  "How do you coach a career-changer with no sales background?",
  "How do you coach a new manager's first hire through onboarding?",
  "How do you coach a new rep to pass their certification?",
  "How do you set first-90-day milestones that actually predict success?",
  "How do you coach a new rep to handle their first tough objection?",
  "How do you coach a recent grad on professional sales habits?",

  // ── L. Slumps / mindset / motivation / burnout ──
  "How do you coach a rep out of a sales slump?",
  "How do you coach a rep who's lost their confidence?",
  "How do you coach a rep who's burned out?",
  "How do you coach a rep who's afraid of failing publicly?",
  "How do you coach a rep who takes rejection personally?",
  "How do you coach a rep whose head isn't in the game?",
  "How do you coach a rep through a personal hard time?",
  "How do you coach a rep who's lost motivation after a missed quarter?",
  "How do you coach a rep to build mental resilience?",
  "How do you coach a rep who's anxious before big calls?",
  "How do you coach a rep to manage their energy through a long quarter?",
  "How do you coach a rep who's comparing themselves to top performers?",
  "How do you coach a rep who's thinking about quitting?",
  "How do you coach a rep to bounce back from a lost deal?",
  "How do you keep a rep motivated when they're behind on quota?",

  // ── M. Top performers / veterans / retention ──
  "How do you coach a top performer who thinks they don't need coaching?",
  "How do you coach a veteran rep set in their ways?",
  "How do you keep your best rep from leaving?",
  "How do you coach a top rep to scale their playbook to the team?",
  "How do you coach a high performer to take on more responsibility?",
  "How do you coach a top rep who's become arrogant?",
  "How do you coach a star rep to mentor junior reps?",
  "How do you challenge a top performer who's plateaued?",
  "How do you coach a tenured rep through a product or market shift?",
  "How do you coach a top rep to stop relying on one big account?",

  // ── N. Coaching mechanics & programs ──
  "How do you structure a weekly 1:1 that reps look forward to?",
  "How do you run a call review that changes behavior?",
  "How do you build a sales coaching scorecard?",
  "How do you set up a role-play program reps don't dread?",
  "How do you run group coaching without it feeling like a lecture?",
  "How do you build a peer coaching program on your team?",
  "How do you coach reps asynchronously across time zones?",
  "How do you give coaching feedback right after a live call?",
  "How do you run a win-loss review that the whole team learns from?",
  "How do you use call recordings to coach at scale?",
  "How do you build a coaching cadence for a team of ten reps?",
  "How do you coach when you have no time in your calendar?",
  "How do you decide which reps to spend your coaching time on?",
  "How do you run a deal review without taking over the deal?",
  "How do you build a library of best-practice call snippets?",
  "How do you certify reps on a new pitch or product?",
  "How do you coach reps using a call-scoring rubric?",
  "How do you make coaching stick between 1:1s?",
  "How do you run a skills bootcamp for the whole team?",
  "How do you coach reps to self-assess their own calls?",

  // ── O. Manager development / coaching the coaches ──
  "How do you coach a frontline manager to become a great coach?",
  "How do you teach a new sales manager to run their first 1:1?",
  "How do you coach a manager who promotes their reps' deals too optimistically?",
  "How do you coach a manager who's still selling instead of leading?",
  "How do you coach a manager to hold reps accountable without micromanaging?",
  "How do you coach a manager to have a hard performance conversation?",
  "How do you coach a manager whose team is missing quota?",
  "How do you coach a manager to forecast their team accurately?",
  "How do you coach a manager to delegate instead of doing it themselves?",
  "How do you coach a manager to build their own coaching cadence?",
  "How do you coach a second-line leader to develop their managers?",
  "How do you coach a manager to run an effective team meeting?",
  "How do you coach a manager who avoids conflict with their reps?",
  "How do you coach a newly promoted manager who's coaching former peers?",
  "How do you coach a manager to read their team's leading indicators?",

  // ── P. Metrics / ROI / culture ──
  "How do you measure whether your sales coaching is working?",
  "How do you prove the ROI of sales coaching to leadership?",
  "How do you build a culture where reps want to be coached?",
  "How do you track coaching activity without it becoming busywork?",
  "How do you tie coaching to specific revenue outcomes?",
  "How do you benchmark your team's coaching against the best teams?",
  "How do you use leading indicators to focus your coaching?",
  "How do you set coaching goals for each rep on the team?",
  "How do you know when coaching isn't the answer?",
  "How do you build a coaching scorecard for your managers?",
  "How do you get executive buy-in for a coaching program?",
  "How do you sustain a coaching habit when the quarter gets busy?",

  // ── Q. 2027 context: AI, hybrid, market ──
  "How do you coach reps to use AI tools without losing their selling skills?",
  "How do you coach reps to sell in a tighter 2027 budget environment?",
  "How do you coach reps to navigate longer 2027 buying cycles?",
  "How do you coach a hybrid team that's part remote, part in-office?",
  "How do you coach reps to sell to a larger buying committee?",
  "How do you coach reps to use AI call summaries to improve faster?",
  "How do you coach reps to handle 'we're cutting costs this year'?",
  "How do you coach reps to multithread when buyers keep changing?",
  "How do you coach reps to sell value in a down market?",
  "How do you coach reps to use AI for research and personalization?",
  "How do you coach a fully remote sales team to stay sharp?",
  "How do you coach reps to handle deals with more approval layers?",
  "How do you coach reps when deal sizes are shrinking?",
  "How do you coach reps to sell into a no-decision market?",
  "How do you coach reps to use conversation intelligence tools well?",
  "How do you coach reps to adapt when the ICP shifts mid-year?",
  "How do you coach reps to compete against a free or cheaper tool?",
  "How do you coach reps to keep buyers engaged in a long evaluation?",
  "How do you coach reps to sell during a company reorg?",
  "How do you coach reps to handle procurement adding new hurdles?",

  // ── R. Extra depth to reach 300 ──
  "How do you coach a rep to run a better quarterly business review?",
  "How do you coach a rep to expand a single-product account?",
  "How do you coach a rep to reduce churn in their book of business?",
  "How do you coach a rep to win back a lost customer?",
  "How do you coach a rep to handle a renewal that's at risk?",
  "How do you coach a rep to sell a price increase to existing customers?",
  "How do you coach a rep to cross-sell a second product line?",
  "How do you coach a rep to build a business case for the buyer's CFO?",
  "How do you coach a rep to present to a board or executive team?",
  "How do you coach a rep to handle a competitive bake-off?",
  "How do you coach a rep to respond to an RFP strategically?",
  "How do you coach a rep to build champions inside an account?",
  "How do you coach a rep to recover a stalled enterprise deal?",
  "How do you coach a rep to sell through a partner or reseller?",
  "How do you coach a rep to handle a deal with a long pilot phase?",
  "How do you coach a rep to manage a deal across multiple regions?",
  "How do you coach a rep to keep momentum over a long sales cycle?",
  "How do you coach a rep to handle a buyer who ghosts after the proposal?",
  "How do you coach a rep to qualify an inbound enterprise lead?",
  "How do you coach a rep to turn a small pilot into a full rollout?",
  "How do you coach a rep to sell to a skeptical technical buyer?",
  "How do you coach a rep to handle a buyer who wants everything in writing?",
  "How do you coach a rep to manage a deal when the champion leaves?",
  "How do you coach a rep to navigate a deal with competing internal priorities?",
  "How do you coach a rep to sell a complex solution simply?",
  "How do you coach a rep to handle a buyer who keeps moving the goalposts?",
  "How do you coach a rep to close a deal before the buyer's budget expires?",
  "How do you coach a rep to handle a deal that needs board approval?",
  "How do you coach a rep to sell a new product with no track record?",
  "How do you coach a rep to re-engage a deal that stalled for months?",
  "How do you coach a rep to handle a buyer who only talks to your competitor?",
  "How do you coach a rep to sell into an account that already churned once?",
  "How do you coach a rep to run a tight trial or evaluation period?",
  "How do you coach a rep to get a meeting with the real decision maker?",
  "How do you coach a rep to handle a deal where the buyer has no urgency?",
  "How do you coach a rep to sell a platform instead of a point solution?",
  "How do you coach a rep to keep a deal alive through a budget freeze?",
  "How do you coach a rep to handle a buyer who wants a custom build?",
  "How do you coach a rep to close a deal that's been open too long?",
  "How do you coach a rep to win a deal against an incumbent vendor?",
  "How do you coach a rep to handle a champion who suddenly goes quiet?",
  "How do you coach a rep to qualify a deal that looks too good to be true?",
  "How do you coach a rep to sell to a committee that can't agree?",
  "How do you coach a rep to handle a buyer who keeps asking for references?"
];

// Normalize for dedup (lowercase, strip punctuation, collapse spaces, drop trailing year).
const norm = s => s.toLowerCase().replace(/[^a-z0-9 ]/g, ' ').replace(/\b20\d\d\b/g, '').replace(/\s+/g, ' ').trim();
const slugify = s => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').split('-').slice(0, 8).join('-');

const existing = require('./_manifest_cg.json').map(x => norm(x.title));
const existingSet = new Set(existing);

// Dedup the new list internally + against existing.
const seen = new Set();
const dups = [];
const clean = [];
for (const q of Q) {
  const n = norm(q);
  if (existingSet.has(n)) { dups.push('EXISTS: ' + q); continue; }
  if (seen.has(n)) { dups.push('INTERNAL DUP: ' + q); continue; }
  seen.add(n);
  clean.push(q);
}

console.log('authored:', Q.length, ' clean:', clean.length, ' collisions:', dups.length);
if (dups.length) { dups.forEach(d => console.log('  ' + d)); }
if (clean.length < 300) console.log('WARNING: fewer than 300 clean topics (' + clean.length + '). Add more.');

const manifest = clean.slice(0, 300).map((title, i) => {
  const id = 'cg' + String(201 + i).padStart(4, '0');
  return { id, title, slug: slugify(title) };
});
fs.writeFileSync('C:/Users/koryj/website/_manifest_cg2.json', JSON.stringify(manifest, null, 1));
console.log('wrote _manifest_cg2.json with', manifest.length, 'topics (', manifest[0].id, '→', manifest[manifest.length - 1].id, ')');
