// Generate _cg_keyword_phrases.json — 300 Pulse Coaching SEO phrases (6 × 50).
// PILLAR LAW: maintain 1:1 Top-10 titles vs operator Q&A questions — .cursor/rules/coaching-pillar-mix.mdc
const fs = require('fs');

const CORE = [
  'Sales coaching for managers',
  'How to coach sales reps effectively',
  'Sales manager coaching guide 2027',
  'One-on-one sales coaching framework',
  'Weekly sales coaching cadence',
  'Sales coaching conversation scripts',
  'GROW model sales coaching',
  'Coaching sales reps on prospecting',
  'Coaching sales reps on discovery',
  'Coaching sales reps on closing',
  'Coaching sales reps on pipeline hygiene',
  'Coaching sales reps on forecasting',
  'Coaching sales reps on objection handling',
  'Coaching sales reps on negotiation',
  'Coaching sales reps on demo skills',
  'Coaching sales reps on qualification',
  'Coaching sales reps on follow-up',
  'Coaching sales reps on time management',
  'Coaching sales reps on CRM hygiene',
  'Coaching sales reps on activity metrics',
  'Sales coaching plan template',
  '30-60-90 day sales coaching plan',
  'Sales coaching scorecard for managers',
  'Call coaching framework for sales',
  'Deal coaching session agenda',
  'Pipeline coaching meeting format',
  'Sales coaching using Gong call reviews',
  'Sales coaching with conversation intelligence',
  'Field coaching ride-along checklist',
  'Sales coaching for new managers',
  'Sales coaching for first-time managers',
  'Sales coaching for remote teams',
  'Sales coaching for hybrid sales teams',
  'Sales coaching for SaaS reps',
  'B2B sales coaching best practices',
  'Enterprise sales coaching techniques',
  'Mid-market sales coaching playbook',
  'SMB sales coaching tips',
  'Sales coaching for quota attainment',
  'Sales coaching for ramping reps',
  'Sales coaching for underperformers',
  'Sales coaching for top performers',
  'Sales coaching for plateaued reps',
  'Sales coaching for new hires',
  'Sales coaching during onboarding',
  'Sales coaching after a lost deal',
  'Sales coaching before a big presentation',
  'Sales coaching for end-of-quarter push',
  'Sales coaching for annual planning',
  'Sales coaching metrics that matter',
];

const PROBLEM = [
  'How to coach a rep who will not prospect',
  'How to coach a rep who sandbags the forecast',
  'How to coach a rep who discounts too early',
  'How to coach a rep who single-threads deals',
  'How to coach a rep who skips discovery',
  'How to coach a rep who demos too much',
  'How to coach a rep who cannot close',
  'How to coach a rep who misses quota repeatedly',
  'How to coach a rep who resists feedback',
  'How to coach a rep who ignores the CRM',
  'How to coach a rep who has happy ears',
  'How to coach a rep who chases bad deals',
  'How to coach a rep who stalls at proposal stage',
  'How to coach a rep who loses deals on price',
  'How to coach a rep who cannot handle objections',
  'How to coach a rep who talks too much on calls',
  'How to coach a rep who is afraid of executives',
  'How to coach a rep who avoids asking for the sale',
  'How to coach a rep who overpromises buyers',
  'How to coach a rep who is inconsistent month to month',
  'How to coach a rep who will not role-play',
  'How to coach a rep who blames marketing for pipeline',
  'How to coach a rep who blames product for losses',
  'How to coach a rep who will not multi-thread',
  'How to coach a rep who cannot build urgency',
  'How to coach a rep who gives away free pilots',
  'How to coach a rep who cannot qualify budget',
  'How to coach a rep who takes buyer words at face value',
  'How to coach a rep who is great at demos but weak at discovery',
  'How to coach a rep who is active but unproductive',
  'How to coach a rep who is smart but lazy',
  'How to coach a rep who is hardworking but unskilled',
  'How to coach a rep who oversells and creates churn',
  'How to coach a rep who will not follow the sales process',
  'How to coach a rep who is weak on video calls',
  'How to coach a rep who chases small easy deals',
  'How to coach a rep who cannot recover stalled deals',
  'How to coach a rep who loses to the same competitor',
  'How to coach a rep who cannot articulate value',
  'How to coach a rep who struggles with procurement',
  'How to coach a rep who cannot run a mutual action plan',
  'How to coach a rep who avoids difficult conversations',
  'How to coach a rep who is burned out',
  'How to coach a rep who is disengaged',
  'How to coach a rep who is defensive in 1:1s',
  'How to coach a rep who will not practice',
  'How to coach a rep who cannot handle rejection',
  'How to coach a rep who needs a performance plan',
  'How to coach a rep when coaching is not working',
  'When to coach versus when to manage out',
];

const PEOPLE = [
  'Emotional intelligence in sales coaching',
  'Building trust with sales reps as a manager',
  'Active listening for sales managers',
  'Giving constructive feedback to sales reps',
  'Radical candor in sales leadership',
  'Coaching reps through imposter syndrome',
  'Coaching reps on executive presence',
  'Coaching reps on communication skills',
  'Coaching reps on storytelling in sales',
  'Coaching reps on empathy with buyers',
  'Coaching reps on confidence on calls',
  'Coaching reps on handling stress',
  'Coaching reps on resilience after rejection',
  'Coaching reps on self-awareness',
  'Coaching reps on growth mindset',
  'Coaching reps on accountability',
  'Coaching reps on ownership mentality',
  'Coaching reps on teamwork in pod selling',
  'Coaching reps on cross-functional collaboration',
  'Coaching reps on professionalism with buyers',
  'Coaching reps on written communication',
  'Coaching reps on presentation skills',
  'Coaching reps on listening more than talking',
  'Coaching reps on reading buyer body language',
  'Coaching reps on building rapport without wasting time',
  'Coaching reps on curiosity in discovery',
  'Coaching reps on patience in long sales cycles',
  'Coaching reps on adaptability to buyer styles',
  'Coaching reps on cultural sensitivity in global deals',
  'Coaching reps on ethics and integrity in sales',
  'Coaching reps on managing up to leadership',
  'Coaching reps on peer feedback culture',
  'Coaching reps on receiving criticism',
  'Coaching reps on motivation without toxic positivity',
  'Coaching reps on work-life balance',
  'Coaching reps on avoiding burnout',
  'Coaching reps on mental health awareness',
  'Coaching reps on inclusion on diverse teams',
  'Coaching women in sales leadership paths',
  'Coaching early-career sales reps',
  'Coaching veteran reps who resist change',
  'Coaching introverted sales reps',
  'Coaching extroverted reps who talk over buyers',
  'Coaching reps on humility after a big win',
  'Coaching reps on learning from losses',
  'Coaching reps on personal brand on LinkedIn',
  'Coaching reps on networking for pipeline',
  'Coaching reps on internal politics navigation',
  'Coaching reps on asking for help',
  'Coaching reps on celebrating small wins',
];

const ROLE = [
  'SDR coaching playbook for managers',
  'BDR coaching on outbound messaging',
  'AE coaching for enterprise deals',
  'AE coaching for mid-market deals',
  'Inside sales rep coaching guide',
  'Field sales rep coaching guide',
  'Account manager coaching for expansion',
  'Customer success coaching for upsell',
  'Sales engineer coaching for presales',
  'Channel partner manager coaching',
  'Renewals rep coaching framework',
  'Full-cycle rep coaching balance',
  'Hunter rep coaching for new logos',
  'Farmer rep coaching for retention',
  'Overlay specialist coaching without quota',
  'Sales development manager coaching SDRs',
  'Frontline sales manager coaching AEs',
  'Regional VP coaching sales managers',
  'Enablement leader coaching program design',
  'RevOps coaching managers on data',
  'Coaching SDRs on meeting show rates',
  'Coaching SDRs on research before outreach',
  'Coaching SDRs on handoff to AEs',
  'Coaching AEs on inherited messy pipeline',
  'Coaching AEs on multi-year contracts',
  'Coaching AEs on executive sponsorship',
  'Coaching AEs on mutual action plans',
  'Coaching AEs on MEDDPICC adoption',
  'Coaching AEs on Challenger teach moments',
  'Coaching AEs on SPIN discovery questions',
  'Coaching AEs on Sandler up-front contracts',
  'Coaching AEs on Command of the Message',
  'Coaching AEs on business value selling',
  'Coaching AEs on proof of concept design',
  'Coaching AEs on procurement navigation',
  'Coaching AEs on security review cycles',
  'Coaching AEs on competitive displacement',
  'Coaching AEs on land-and-expand motions',
  'Coaching AEs on usage-based selling',
  'Coaching AEs on PLG sales-assist handoffs',
  'Coaching CSMs to spot expansion signals',
  'Coaching CSMs on renewal risk conversations',
  'Coaching partner reps on co-sell motions',
  'Coaching new SDR through first 30 days',
  'Coaching new AE through first 90 days',
  'Coaching promoted rep into management',
  'Coaching rep moving from SMB to enterprise',
  'Coaching rep transitioning to remote selling',
  'Coaching rep adopting AI sales tools',
  'Coaching rep on first enterprise deal',
];

const COMPARATIVE = [
  'GROW model vs Situational Leadership for sales coaching',
  'Challenger coaching vs relationship selling coaching',
  'MEDDIC coaching vs SPIN coaching for AEs',
  'Gong coaching vs manual call review coaching',
  'AI sales coaching vs manager-led coaching',
  'Group coaching vs one-on-one sales coaching',
  'Peer coaching circles for sales teams',
  'Enablement-led coaching vs manager-led coaching',
  'External sales coach vs internal manager coaching',
  'Sales training vs ongoing sales coaching',
  'Coaching vs managing sales performance',
  'Coaching vs pip for underperforming reps',
  'Coaching vs mentoring in sales organizations',
  'Coaching vs telling in sales leadership',
  'Deal coaching vs skill coaching',
  'Call coaching vs pipeline coaching',
  'Frontline coaching vs skip-level coaching',
  'Weekly coaching vs monthly coaching cadence',
  'Structured coaching vs informal coaching',
  'Coaching frameworks comparison for SaaS',
  'Best sales coaching methodology for B2B',
  'Best sales coaching tools for managers 2027',
  'Best conversation intelligence for coaching',
  'Sales coaching software comparison',
  'Gong vs Chorus for sales coaching',
  'Outreach Kaia vs Gong for coaching',
  'Clari vs manual forecast coaching',
  'Sales coaching ROI measurement',
  'Sales coaching impact on win rate',
  'Sales coaching impact on ramp time',
  'Sales coaching impact on quota attainment',
  'Building a sales coaching culture',
  'Sales coaching program design for scale',
  'Sales coaching governance for RevOps',
  'Sales coaching metrics dashboard',
  'Manager coaching effectiveness scorecard',
  'Sales coaching budget for mid-market SaaS',
  'Sales coaching for PE-backed portfolio companies',
  'Sales coaching after a merger integration',
  'Sales coaching for post-layoff morale',
  'Sales coaching during a GTM pivot',
  'Sales coaching when launching a new product',
  'Sales coaching for new market entry',
  'Sales coaching for pricing changes',
  'Sales coaching for comp plan changes',
  'Strategic sales coaching for CROs',
  'Sales coaching aligned to revenue architecture',
  'Sales coaching tied to enablement content',
  'Sales coaching integrated with CRM workflows',
  'Sales coaching strategy for 2027 GTM teams',
];

const LONGTAIL = [
  'How do you run a deal coaching session that moves the deal',
  'How do you coach a rep through a stalled enterprise deal',
  'How do you coach managers to coach their teams',
  'How do you coach a rep who will not update Salesforce',
  'How do you coach a rep on multi-threading a buying committee',
  'How do you coach a rep to find the economic buyer',
  'How do you coach a rep to quantify pain in dollars',
  'How do you coach a rep to build a champion',
  'How do you coach a rep to run a business case',
  'How do you coach a rep on mutual close plans',
  'How do you coach a rep after three losses in a row',
  'How do you coach a rep who is great at top of funnel but weak at close',
  'How do you coach a rep on handling ghosting buyers',
  'How do you coach a rep on competitive takeout campaigns',
  'How do you coach a rep on selling against incumbents',
  'How do you coach a rep on selling to technical buyers',
  'How do you coach a rep on selling to economic buyers',
  'How do you coach a rep on selling to procurement',
  'How do you coach a rep on legal redline negotiations',
  'How do you coach a rep on security questionnaire responses',
  'How do you coach a rep on pilot-to-paid conversion',
  'How do you coach a rep on expansion within an account',
  'How do you coach a rep on whitespace mapping',
  'How do you coach a rep on territory planning',
  'How do you coach a rep on account prioritization',
  'How do you coach a rep on outbound personalization at scale',
  'How do you coach a rep on LinkedIn social selling',
  'How do you coach a rep on cold call openings',
  'How do you coach a rep on email sequences that get replies',
  'How do you coach a rep on booking executive meetings',
  'How do you coach a rep on running effective QBRs with buyers',
  'How do you coach a rep on handling RFPs without discounting',
  'How do you coach a rep on multi-product cross-sell',
  'How do you coach a rep on selling professional services attach',
  'How do you coach a rep on usage data in renewal conversations',
  'How do you coach a rep when the product has known gaps',
  'How do you coach a rep when territory is too small',
  'How do you coach a rep when comp plan feels unfair',
  'How do you coach a rep who wants to become a manager',
  'How do you coach a rep returning from parental leave',
  'How do you coach a rep on AI-assisted call prep',
  'How do you coach a rep on using AI without sounding robotic',
  'How do you coach a rep on shorter buying cycles in 2027',
  'How do you coach a rep on selling to AI-native buyers',
  'How do you coach a rep on committee selling in SaaS',
  'How do you coach a rep on value engineering conversations',
  'How do you coach a rep on executive storytelling',
  'How do you coach a rep on forecasting with integrity',
  'How do you coach a rep on commit versus best case pipeline',
  'How do you coach a rep on turning around a bad quarter',
];

const ALL = [...CORE, ...PROBLEM, ...PEOPLE, ...ROLE, ...COMPARATIVE, ...LONGTAIL];
const uniq = [...new Set(ALL.map((s) => s.trim()))];
if (uniq.length !== 300) {
  console.error('Expected 300 unique phrases, got', uniq.length);
  process.exit(1);
}
fs.writeFileSync('C:/Users/koryj/website/_cg_keyword_phrases.json', JSON.stringify(uniq, null, 2) + '\n');
console.log('wrote', uniq.length, 'phrases');
