// Competitive landscape + industry/functional + expanded tactical CRO/GTM/RevOps keywords.
// Merged into _cro_seo_keywords.js → static pages + library blob SEO tags.

/** Direct/indirect fractional CRO & GTM market players */
const CRO_COMPETITIVE_LANDSCAPE = [
  'Sales Xceleration',
  'Sales Xceleration alternative',
  'Chief Outsiders',
  'Chief Outsiders alternative',
  'Vendux',
  'Vendux alternative',
  'Bolster',
  'Bolster fractional CRO',
  'Bolster executive marketplace',
  'Toptal',
  'Toptal fractional CRO',
  'GTM 80/20',
  'GTM 80/20 alternative',
  'Kalungi',
  'Kalungi alternative',
  'CMOx',
  'CMOx alternative',
  'Waveup',
  'Waveup GTM',
  'SBI Growth',
  'SBI Growth alternative',
  'Brevet',
  'Brevet revenue consulting',
  'GrowthExpertz',
  'GrowthExpertz alternative',
  'Crucial Recruiting',
  'Crucial Recruiting TaaS',
  'SLED Sales',
  'MarketerHire',
  'MarketerHire alternative',
  'Catalant',
  'Catalant alternative',
  'GoFractional',
  'GoFractional alternative',
  'Fractionus',
  'Chameleon Collective',
  'TechCXO',
  'Mahdlo Executive Advisors',
  'Valenta',
  'Vation Ventures',
  'Aiken House',
  'Pavilion fractional CRO',
  'Bespoke Partners',
  'RevenueReady',
];

/** GTM frameworks, RevOps, engagement types, outcomes, segments */
const CRO_INDUSTRY_FUNCTIONAL = [
  'GTM Roadmap',
  'Revenue Playbook',
  'Sales Machine',
  'Revenue Architecture',
  'CSCORE',
  'CSCORE model',
  'Revenue Systems',
  'Sales Stack',
  'Revenue Data',
  'KPI Alignment',
  'Funnel Optimization',
  'Interim Executive',
  'Embedded Leadership',
  'Fractional Advisor',
  'Strategic Consultant',
  'Fractional Talent Marketplace',
  'Revenue Scaling',
  'Pipeline Velocity',
  'CAC/LTV Optimization',
  'ARR Growth',
  'Sales Enablement',
  'Series A Startups',
  'PE-Backed Portfolio',
  'B2B SaaS',
  'Mid-Market Scale-ups',
  'Enterprise Market Entry',
  'GTM operations',
  'GTM strategy',
  'Revenue operations implementation',
  'Go-to-market architecture',
  'Revenue engine optimization',
  'Sales-Led Growth',
  'Product-Led Growth',
  'Account-Based Selling',
  'Funnel velocity metrics',
  'SDR workflow optimization',
  'CRM as a single source of truth',
  'Lead routing automation',
  'Buyer persona segmentation',
  'Revenue tech stack auditing',
  'Net Revenue Retention',
  'Lead-to-cash process',
  'CRM architecture optimization',
];

/** Expanded tactical fractional CRO / RevOps / GTM phrases */
const CRO_EXPANDED_TACTICAL = [
  'Fractional Revenue Transformation',
  'Fractional GTM Alignment',
  'Fractional Sales Ecosystem Expert',
  'Fractional Revenue Value Prop Consultant',
  'Fractional Sales Messaging Lead',
  'Fractional Revenue Retention Strategy',
  'Fractional Sales Tech Integration',
  'Fractional Revenue Tech Audit',
  'Fractional Sales Pipeline Velocity',
  'Fractional GTM Strategy Partner',
  'Fractional Sales Compensation Architect',
  'Fractional Revenue Forecasting Specialist',
  'Fractional Sales Territory Optimizer',
  'Fractional Revenue Talent Consultant',
  'Fractional Sales Enablement Architect',
  'Fractional Revenue Dashboards Lead',
  'Fractional Sales Incentive Strategist',
  'Fractional Revenue Cycle Manager',
  'Fractional Sales Channel Strategist',
  'Fractional Revenue Growth Architect',
  'Fractional Sales Productivity Coach',
  'Fractional Revenue Data Analyst',
  'Fractional Sales Process Designer',
  'Fractional Revenue Workflow Auditor',
  'Fractional Sales Infrastructure Builder',
  'Fractional Revenue Systems Architect',
  'Fractional Sales Strategy Mentor',
  'Fractional Revenue Policy Consultant',
  'Fractional Sales Culture Advisor',
  'Fractional Revenue Target Planner',
  'Fractional Sales Pipeline Manager',
  'Fractional Revenue Reporting Specialist',
  'Fractional Sales Funnel Architect',
  'Fractional Revenue Model Builder',
  'Fractional Sales Playbook Creator',
  'Fractional Revenue Strategy Planner',
  'Fractional Sales Performance Analyst',
  'Fractional Revenue Growth Hacker',
  'Fractional Sales Automation Expert',
  'Fractional Revenue Tech Stack Lead',
  'Fractional Sales Hiring Specialist',
  'Fractional Revenue Onboarding Coach',
  'Fractional Sales Training Consultant',
  'Fractional Revenue Retention Expert',
  'Fractional Sales Churn Reduction Lead',
  'Fractional Revenue Customer Journey Map',
  'Fractional Sales Account Expansion Lead',
  'Fractional Revenue Upsell Strategist',
  'Fractional Sales Referral Partner',
  'Fractional Revenue Pricing Consultant',
  'Fractional Sales Discounting Strategy',
  'Fractional Revenue Margin Optimizer',
  'Fractional Sales Revenue Operations Lead',
  'Fractional Revenue Data Governance',
  'Fractional Sales CRM Architect',
  'Fractional Revenue Tech Selection',
  'Fractional Sales Tool Implementation',
  'Fractional Revenue API Strategy',
  'Fractional Sales Integration Consultant',
  'Fractional Revenue Dashboard Designer',
  'Fractional Sales Scorecard Creator',
  'Fractional Revenue Metric Architect',
  'Fractional Sales KPI Designer',
  'Fractional Revenue Milestone Planner',
  'Fractional Sales Growth Roadmapper',
  'Fractional Revenue Scaling Expert',
  'Fractional Sales Expansion Architect',
  'Fractional Revenue Market Entry Lead',
  'Fractional Sales Segment Strategy',
  'Fractional Revenue ICP Definition',
  'Fractional Sales Persona Builder',
  'Fractional Revenue Value Mapping',
  'Fractional Sales Narrative Consultant',
  'Fractional Revenue Pitch Deck Designer',
  'Fractional Sales Demo Optimization',
  'Fractional Revenue Proposal Architect',
  'Fractional Sales Contract Strategist',
  'Fractional Revenue Legal Alignment',
  'Fractional Sales Renewals Expert',
  'Fractional Revenue Expansion Lead',
  'Fractional Sales Portfolio Manager',
  'Fractional Revenue Unit Economics',
  'Fractional Sales CAC/LTV Analyst',
  'Fractional Revenue Runway Planner',
  'Fractional Sales Burn Rate Consultant',
  'Fractional Revenue ARR Strategist',
  'Fractional Sales Retention Metrician',
  'Fractional Revenue Churn Analyst',
  'Fractional Sales Win Rate Auditor',
  'Fractional Revenue Cycle Time Analyst',
  'Fractional Sales Lead Gen Strategy',
  'Fractional Revenue Inbound Lead Lead',
  'Fractional Sales Outbound Architect',
  'Fractional Revenue SDR Management',
  'Fractional Sales BDR Strategy',
  'Fractional Revenue AE Coach',
  'Fractional Sales SE Management',
  'Fractional Revenue CS Alignment',
  'Fractional Sales Marketing Sync',
  'Fractional Revenue Brand Integration',
  'Fractional Sales PR Alignment',
  'Fractional Revenue Event Strategist',
  'Fractional Sales Trade Show Lead',
  'Fractional Revenue Content Strategy',
  'Fractional Sales Collateral Designer',
  'Fractional Revenue Social Selling',
  'Fractional Sales LinkedIn Strategy',
  'Fractional Sales Linked-In Strategy',
  'Fractional Revenue Thought Leadership',
  'Fractional Sales Expert Branding',
  'Fractional Revenue Speaker',
  'Fractional Sales Mentor',
  'Fractional Revenue Advisor',
  'Fractional Sales Strategist',
  'Fractional Revenue Consultant',
  'Fractional Sales Coach',
  'Fractional Revenue Operations',
  'Fractional Revenue Operations Lead',
  'Fractional Sales Systems',
  'Fractional Revenue Infrastructure',
  'Fractional Sales Performance',
  'Fractional Revenue Growth',
  'Fractional Sales Optimization',
  'Fractional Revenue Strategy',
  'Fractional Sales Pipeline',
  'Fractional Revenue Funnel',
  'Fractional Sales Efficiency',
  'Fractional Revenue Forecasting',
  'Fractional Sales Analytics',
  'Fractional Revenue Tech',
  'Fractional Sales Process',
  'Fractional Revenue Roadmap',
  'Fractional Revenue Alignment',
  'Fractional Sales Hiring',
  'Fractional Revenue Compensation',
  'Fractional Sales Territory',
  'Fractional Revenue Channel',
  'Fractional Sales Prospecting',
  'Fractional Revenue Closing',
  'Fractional Sales Scaling',
  'Fractional Revenue Management',
  'Fractional Sales Audit',
  'Fractional Revenue Operations Consulting',
  'Fractional Sales Strategy Consulting',
  'Fractional Revenue Growth Consulting',
  'Fractional Sales Performance Consulting',
  'Fractional Revenue Optimization Consulting',
  'Fractional Sales Transformation Consulting',
  'Fractional Revenue Architecture Consulting',
  'Fractional Sales Systems Consulting',
  'Fractional Revenue Infrastructure Consulting',
  'Fractional Sales Pipeline Consulting',
  'Fractional Revenue Funnel Consulting',
  'Fractional Sales Efficiency Consulting',
  'Fractional Revenue Forecasting Consulting',
  'Fractional Sales Analytics Consulting',
  'Fractional Revenue Tech Consulting',
  'Fractional Sales Enablement Consulting',
  'Fractional Sales Process Consulting',
  'Fractional Revenue Roadmap Consulting',
  'Fractional Sales Training Consulting',
  'Fractional Revenue Alignment Consulting',
  'Fractional Sales Hiring Consulting',
  'Fractional Revenue Compensation Consulting',
  'Fractional Sales Territory Consulting',
  'Fractional Revenue Channel Consulting',
  'Fractional Sales Prospecting Consulting',
  'Fractional Revenue Closing Consulting',
  'Fractional Sales Scaling Consulting',
  'Fractional Revenue Management Consulting',
  'Fractional Sales Audit Consulting',
  'Fractional Revenue Mentor Consulting',
  'Fractional Sales Leadership Consulting',
  'Fractional Revenue Strategy Advisor',
  'Fractional Sales Strategy Advisor',
  'Fractional Growth Strategy Advisor',
  'Fractional GTM Strategy Advisor',
  'Fractional Sales Operations Advisor',
  'Fractional Revenue Operations Advisor',
  'Fractional Sales Enablement Advisor',
  'Fractional Revenue Enablement Advisor',
  'Fractional Sales Performance Advisor',
  'Fractional Revenue Performance Advisor',
  'Fractional Sales Scaling Advisor',
  'Fractional Sales Transformation Advisor',
  'Fractional Revenue Transformation Advisor',
  'Fractional Sales Leadership Advisor',
  'Fractional Revenue Leadership Advisor',
  'Fractional Sales Growth Advisor',
  'Fractional Revenue Growth Advisor',
];

const CRO_LANDSCAPE_ALL = [
  ...CRO_COMPETITIVE_LANDSCAPE,
  ...CRO_INDUSTRY_FUNCTIONAL,
  ...CRO_EXPANDED_TACTICAL,
];

module.exports = {
  CRO_COMPETITIVE_LANDSCAPE,
  CRO_INDUSTRY_FUNCTIONAL,
  CRO_EXPANDED_TACTICAL,
  CRO_LANDSCAPE_ALL,
};
