// 100 fractional CRO / revenue leadership SERP phrases — cro-syndicate-team + CRO pages.
const FRACTIONAL_CRO_100 = [
  'Fractional CRO',
  'Fractional Chief Revenue Officer',
  'Part-time CRO',
  'Interim CRO',
  'Fractional Revenue Lead',
  'Fractional Sales Executive',
  'Fractional Sales Leadership',
  'Fractional Go-To-Market Lead',
  'GTM Fractional Consultant',
  'Revenue Operations Consultant',
  'Fractional Head of Sales',
  'Fractional VP of Sales',
  'Fractional Sales Strategy',
  'Fractional Growth Executive',
  'Fractional Sales Director',
  'Fractional Revenue Consultant',
  'On-demand CRO',
  'Revenue Growth Advisor',
  'Sales Scaling Consultant',
  'Fractional Commercial Lead',
  'Fractional B2B Sales Leader',
  'Revenue Strategy Consultant',
  'Fractional Pipeline Expert',
  'Fractional Sales Operations',
  'Fractional Revenue Architect',
  'Fractional Growth Partner',
  'Fractional Sales Coach',
  'Fractional CRO Services',
  'Fractional Sales Management',
  'Fractional GTM Strategist',
  'Sales Performance Consultant',
  'Revenue Acceleration Expert',
  'Fractional Sales Transformation',
  'Revenue Systems Consultant',
  'Fractional VP of Revenue',
  'Fractional Growth Strategist',
  'Sales Workflow Consultant',
  'Revenue Optimization Expert',
  'Fractional Sales Audit',
  'Fractional Revenue Mentor',
  'Fractional Sales Infrastructure',
  'Fractional Sales Channel Expert',
  'Revenue Playbook Consultant',
  'Fractional Enterprise Sales Leader',
  'Fractional SaaS Sales Expert',
  'Fractional Sales Hiring Consultant',
  'Revenue Tech Stack Advisor',
  'Fractional Sales Training',
  'Fractional Sales Alignment',
  'Fractional Sales Process Consultant',
  'Fractional Sales Compensation Expert',
  'Revenue Forecasting Consultant',
  'Fractional Territory Planning',
  'Fractional Sales Enablement',
  'Fractional Revenue Ops Lead',
  'Fractional Growth Operations',
  'Fractional Revenue Culture Lead',
  'Fractional Sales Roadmap Consultant',
  'Fractional Revenue Analytics',
  'Fractional Sales KPI Expert',
  'Fractional Revenue Scaling',
  'Fractional Customer Success Lead',
  'Fractional Account Management Strategy',
  'Fractional Sales Recruitment Consultant',
  'Revenue Funnel Consultant',
  'Fractional Sales Tech Consultant',
  'Fractional Sales Reporting Expert',
  'Fractional Sales Quota Planner',
  'Fractional Sales Strategy Advisor',
  'Revenue Lifecycle Consultant',
  'Fractional Sales Organization Design',
  'Fractional Sales Playbook Architect',
  'Fractional Revenue Model Expert',
  'Fractional Sales Metrics Advisor',
  'Fractional Go-to-Market Coach',
  'Fractional Sales Execution Lead',
  'Fractional Revenue Pilot',
  'Fractional Sales Audit Service',
  'Fractional Revenue Growth Partner',
  'Fractional Sales Change Management',
  'Fractional Sales Pipeline Growth',
  'Fractional Revenue Efficiency Expert',
  'Fractional Sales Team Mentor',
  'Fractional Sales Strategy Review',
  'Fractional Revenue Roadmap Lead',
  'Fractional Sales Structure Expert',
  'Fractional Revenue Alignment Consultant',
  'Fractional Sales Prospecting Lead',
  'Fractional Sales Closing Expert',
  'Fractional Revenue Scaling Advisor',
  'Fractional Sales Process Auditor',
  'Fractional Revenue Strategy Architect',
  'Fractional Sales Velocity Expert',
  'Fractional Revenue Management Lead',
  'Fractional Sales Leadership Support',
  'Fractional Revenue Consulting Group',
  'Fractional Sales Optimization Expert',
  'Fractional GTM Operations',
  'Fractional Revenue Pipeline Audit',
  'Fractional Sales Results Consultant',
];

/** CRO Syndicate + hire-intent phrases layered on cro-syndicate-team */
const CRO_SYNDICATE_TEAM_EXTRA = [
  'CRO Syndicate',
  'CRO Syndicate fractional CRO',
  'CRO Syndicate practitioners',
  'Practitioner CRO',
  'Practitioner Chief Revenue Officer',
  'hire a fractional CRO',
  'hire a CRO',
  'looking to hire a fractional CRO',
  'fractional CRO help',
  'fractional CRO near me',
  'Kory White fractional CRO',
  'Kory White CRO Syndicate',
  'best fractional CRO',
  'fractional CRO Maryland',
  'fractional CRO Washington DC',
  'fractional CRO DMV',
];

/** Brand / handle search variants (concatenated + lowercase) */
const KORY_WHITE_BRAND_EXTRA = [
  'korywhite',
  'kory white',
  'korywhitemaryland',
  'korywhitemd',
];

/** Expertise / industry credential strip — Kory White + CRO Syndicate landing pages */
const KORY_WHITE_EXPERTISE_EXTRA = [
  'Chief Revenue Officer',
  'SaaS',
  'Telco',
  'B2B',
  'B2C',
  'Events',
  'Call Centers',
  'Lead Gen',
  'Architect',
  'Revenue Architect',
  '$200M Builder',
  '$3B Scaler',
  '200M revenue builder',
  '3B revenue scaler',
  'Leadership Coaching',
  'GTM Playbooks',
  'RevOps',
  'Growth Strategy',
  'Operator',
  'Executive',
  'Kory White SaaS CRO',
  'Kory White Telco CRO',
  'Kory White B2B CRO',
  'Kory White B2C CRO',
  'Kory White call centers',
  'Kory White lead gen',
  'Kory White events CRO',
  'Kory White $200M builder',
  'Kory White $3B scaler',
  'Kory White leadership coaching',
  'Kory White GTM playbooks',
  'Kory White growth strategy',
  'Kory White revenue operator',
  'CRO Syndicate SaaS',
  'CRO Syndicate Telco',
  'CRO Syndicate call centers',
  'CRO Syndicate lead gen',
  'fractional CRO SaaS',
  'fractional CRO Telco',
  'fractional CRO call centers',
  'fractional CRO lead gen',
  'fractional CRO events',
];

function metaKeywordsString() {
  const all = [
    ...FRACTIONAL_CRO_100,
    ...CRO_SYNDICATE_TEAM_EXTRA,
    ...KORY_WHITE_BRAND_EXTRA,
    ...KORY_WHITE_EXPERTISE_EXTRA,
  ];
  return Array.from(new Set(all.map((s) => s.trim()).filter(Boolean))).join(', ');
}

module.exports = {
  FRACTIONAL_CRO_100,
  CRO_SYNDICATE_TEAM_EXTRA,
  KORY_WHITE_BRAND_EXTRA,
  KORY_WHITE_EXPERTISE_EXTRA,
  metaKeywordsString,
};
