// Write _ev_keyword_phrases.json — 200 event SEO phrases (4 sections).
const fs = require('fs');
const PHRASES = [
  // 1-50 corporate/professional
  'Corporate event planning services 2027',
  'Corporate conference management companies',
  'Business conference organizers near [City]',
  'Annual corporate meeting planning checklist',
  'Executive leadership retreat venues',
  'Corporate team building event ideas',
  'Professional networking event planners',
  'B2B trade show planning guide',
  'Corporate product launch event planning',
  'Company town hall meeting production',
  'Sales kickoff event planning 2027',
  'Corporate awards gala planning',
  'Investor relations event management',
  'Shareholder meeting event production',
  'Corporate holiday party planners',
  'Employee appreciation event ideas',
  'Corporate wellness retreat planning',
  'Professional development conference planning',
  'Industry summit event management',
  'Corporate hospitality event services',
  'Board meeting retreat venues',
  'Corporate offsite meeting planners',
  'Hybrid corporate event production',
  'Virtual corporate conference platform comparison',
  'Corporate event budget planning template',
  'Enterprise event security planning',
  'Corporate speaker bureau management',
  'Professional association annual meeting planning',
  'Corporate charity gala fundraising events',
  'Business expo booth planning guide',
  'Corporate VIP reception planning',
  'Executive client entertainment events',
  'Corporate milestone celebration planning',
  'Company anniversary event ideas',
  'Corporate onboarding event experiences',
  'Professional networking mixer planning',
  'Corporate peer group retreat planning',
  'B2B partner summit event design',
  'Corporate thought leadership summit planning',
  'Professional association conference logistics',
  'Corporate DEI event programming ideas',
  'Employee engagement event strategy',
  'Corporate sustainability summit planning',
  'Tech company launch event planning',
  'Pharmaceutical medical congress planning',
  'Financial services conference management',
  'Legal industry conference planning',
  'Healthcare summit event management',
  'Manufacturing trade show strategy',
  'Corporate event ROI measurement framework',
  // 51-100 venue/experience design
  'Event venue design trends 2027',
  'Experiential event design companies',
  'Immersive brand activation venues',
  'Conference center layout best practices',
  'Outdoor event venue staging ideas',
  'Wedding venue design inspiration',
  'Festival grounds experience design',
  'Event lighting design packages',
  'AV production for corporate events',
  'Sound system rental for large events',
  'Event stage design and build',
  'Themed event decor packages',
  'Balloon and floral event installations',
  'Interactive event technology experiences',
  'Projection mapping for events',
  'LED wall rental for conferences',
  'Event furniture rental packages',
  'Luxury tent event venue design',
  'Rooftop event venue styling',
  'Ballroom transformation event design',
  'Museum and gallery event venues',
  'Warehouse loft event venue design',
  'Waterfront event venue experiences',
  'Garden and estate event venues',
  'Historic venue event restoration design',
  'Pop-up event space design',
  'Festival stage production design',
  'Trade show booth experience design',
  'Registration area event flow design',
  'Networking lounge event design',
  'VIP lounge experiential design',
  'Photo booth and social media walls',
  'Event scent branding experiences',
  'Sensory event design techniques',
  'Sustainable event venue design',
  'Zero-waste event production ideas',
  'Event accessibility design standards',
  'Wayfinding signage for large events',
  'Event brand activation installations',
  'Gamification for conference experiences',
  'Hybrid event studio set design',
  'Virtual event backdrop design',
  'Event catering station design',
  'Craft cocktail bar event styling',
  'Food truck festival layout design',
  'Corporate dinner tablescape design',
  'Gala red carpet event design',
  'Festival art installation planning',
  'Event crowd flow and capacity design',
  'Event emergency egress planning design',
  // 101-150 transactional
  'How much does event planning cost',
  'Conference venue rental prices 2027',
  'Corporate event catering cost per person',
  'Wedding venue rental cost [City]',
  'Music festival ticket prices 2027',
  'Trade show booth rental costs',
  'Event AV equipment rental quotes',
  'Event photographer pricing packages',
  'Event videographer cost per hour',
  'DJ vs live band event pricing',
  'Event florist quote estimate guide',
  'Catering quote for 200 guests',
  'Corporate retreat venue pricing packages',
  'Conference registration fee benchmarks',
  'Event insurance cost calculator',
  'Event staffing cost per day',
  'Security guard pricing for events',
  'Portable restroom rental event costs',
  'Event tent rental pricing guide',
  'Chairs and tables rental event costs',
  'Event lighting rental price list',
  'Stage rental cost for corporate events',
  'Photo booth rental packages pricing',
  'Event transportation shuttle quotes',
  'Hotel block rates for conference events',
  'Event production company quote request',
  'Hybrid event platform pricing comparison',
  'Event ticketing platform fees comparison',
  'Event registration software pricing',
  'Event app development cost estimate',
  'Sponsorship packages for corporate events',
  'Event marketing budget template',
  'Gala auction fundraising revenue guide',
  'Corporate event budget breakdown example',
  'Event deposit and cancellation policy template',
  'How to negotiate event venue contracts',
  'Event vendor payment schedule template',
  'Hidden event planning costs to budget',
  'Corporate event per attendee cost benchmarks',
  'Festival vendor booth fee averages',
  'Corporate sponsorship ROI for events',
  'Event break-even ticket price calculator',
  'Group discount event ticket pricing',
  'Early bird event ticket strategy',
  'VIP event package pricing tiers',
  'Event merchandise profit margin guide',
  'Corporate event travel expense budget',
  'Virtual event production cost savings',
  'Event planner retainer fee structure',
  'Full-service event planning package prices',
  // 151-200 long-tail
  'Best music festivals in [City] 2027',
  'Top food festivals in [City] this year',
  'Best concerts in [City] this weekend',
  'Corporate event venues in [City]',
  'Wedding venues in [City] with catering',
  'Conference centers in [City] for 500 guests',
  'Outdoor event spaces in [City]',
  'Rooftop event venues in [City]',
  'Historic event venues in [City]',
  'Affordable event venues in [City]',
  'Luxury gala venues in [City]',
  'Team building activities in [City]',
  'Corporate retreat locations near [City]',
  'Trade show venues in [City]',
  'Festival grounds near [City]',
  "New Year's Eve events in [City] 2027",
  'Fourth of July events in [City]',
  'Christmas holiday events in [City]',
  'Halloween events in [City] for families',
  "St Patrick's Day events in [City]",
  'Pride month events in [City]',
  'Cultural festivals in [City] 2027',
  'Art and craft fairs in [City]',
  'Farmers market events in [City]',
  'Wine and food tasting events [City]',
  'Sporting events calendar [City] 2027',
  'Marathon and running events [City]',
  'Comedy shows in [City] this week',
  'Theater and performing arts [City]',
  'Free events in [City] this weekend',
  'Family-friendly events in [City]',
  'Date night events in [City]',
  'Networking events in [City] professionals',
  'Startup and tech events in [City]',
  'Charity galas and fundraisers [City]',
  'Live music venues in [City] ranked',
  'Night markets and street fairs [City]',
  'Boat and waterfront events [City]',
  'University campus events [City]',
  'Convention schedule [City] 2027',
  'Event parking guide downtown [City]',
  'Public transit to events in [City]',
  'Weather contingency for outdoor events [City]',
  'Best time to visit festivals in [City]',
  'Hidden gem local events in [City]',
  'Event hotels near convention center [City]',
  'Day trips to festivals from [City]',
  'Event shuttle services in [City]',
  'Last-minute event tickets [City]',
  'Event planning companies in [City] ranked',
];
if (PHRASES.length !== 200) {
  console.error('Expected 200 phrases, got', PHRASES.length);
  process.exit(1);
}
const out = 'C:/Users/koryj/website/_ev_keyword_phrases.json';
fs.writeFileSync(out, JSON.stringify(PHRASES, null, 2) + '\n');
console.log('wrote', out, 'count=', PHRASES.length);
