// _gp_themes.js — ORDERED THEME QUEUE for the gp image pool (owner 2026-07-09).
// The generator walks slots in order; each slot's theme = the first band whose `upto` it falls under.
// ~1000 images per theme. `upto` values are cumulative slot ceilings (Star Wars already running to 1600).
// scene × mods gives ~1000+ unique combos per theme; seed + hash-dedup guarantee no repeats.
module.exports.THEMES = [
  {
    name: 'starwars', upto: 1600,
    prompt: 'epic cinematic space opera movie still, Star Wars style, of ',
    tail: ', highly detailed, dramatic, film grain, sweeping composition, sharp focus, 8k',
    mods: ['epic golden-hour desert light', 'cold deep-space starlight', 'dramatic nebula glow', 'fiery explosion light', 'moody hangar lighting', 'hazy twin-sun backlight', 'blue lightsaber glow', 'red villain rim light', 'volumetric god rays through smoke', 'snowy overcast light', 'sunset over alien clouds', 'high-contrast cinematic key light'],
    scenes: [
      'wing-shaped rebel starfighters dogfighting near a moon-sized battle station', 'a hooded space knight igniting a glowing laser sword', 'twin suns setting over a vast desert planet', 'a domed astromech droid rolling across sand dunes', 'a golden humanoid protocol droid in a starship corridor', 'a crowded galactic cantina full of strange aliens', 'a squad of white-armored troopers marching through a hangar', 'a colossal wedge-shaped star destroyer looming over a planet', 'four-legged armored walkers advancing across a snowfield', 'a battered freighter jumping to lightspeed in a streak of stars',
      'a robed old master teaching in a swamp-planet hut', 'a masked dark warlord in flowing black cape and armor', 'a bounty hunter in dented armor with a jetpack', 'a laser-sword duel on a platform above a reactor shaft', 'a fleet of capital ships massing in orbit', 'a moisture farm under a blazing desert sky', 'a carbon-freezing chamber wreathed in steam', 'a forest moon village of tree huts among giant redwoods', 'a podracer speeding through a rocky desert canyon', 'a massive space battle with laser fire and exploding cruisers',
      'a lone starfighter skimming a battle station trench', 'a cloaked figure overlooking a desert canyon at dusk', 'a hangar bay full of parked starfighters and droids', 'a throne room with tall red-armored guards', 'a desert sail barge over dunes at golden hour', 'an ice planet outpost with domed shelters in a blizzard', 'a jungle temple ruin with a landed shuttle', 'a smuggler and a furry copilot in a cockpit', 'a rebel briefing room with a glowing tactical hologram', 'a cliffside monastery on an ocean world at sunset',
      'a dark throne overlooking a fleet through a viewport', 'twin-ion starfighters screaming past a cruiser', 'a desert scavenger leading a pack animal across dunes', 'a rebel pilot climbing into an X-shaped fighter', 'a droid factory line assembling battle droids', 'a cantina band of alien musicians playing', 'a moon-sized station firing a superlaser beam', 'a snow-swept base with parked snow-speeders', 'a cloud city gantry among orange sunset clouds', 'a jedi temple hall lined with tall columns',
      'a bounty hunter ship landing on a stormy platform', 'a lone moon rising over a ringed gas giant', 'a rebel fleet emerging from hyperspace over a planet', 'a jungle canopy with a speeder chase between trees', 'a dark cathedral hangar with a shuttle descending', 'a scavenger picking through a crashed star destroyer in the desert', 'a wise armored bounty hunter with a small green foundling', 'a starfighter squadron flying in formation at dawn', 'a duel on a lava planet with rivers of fire', 'a forest speeder-bike chase at high speed',
      'a desert homestead at twilight with two moons', 'an ancient temple glowing with red crystals', 'a rebel hangar celebration with pilots and droids', 'a lone hooded figure holding a glowing blue blade in the rain', 'a starship graveyard drifting in deep space', 'a cockpit view of a lightspeed jump', 'a rebel command center with holographic star maps', 'a mountaintop hermitage above the clouds', 'a fleet of triangular cruisers eclipsing a sun', 'a lone star knight silhouetted against twin suns',
    ],
  },
  {
    name: 'sports', upto: 2600,
    prompt: 'dynamic cinematic sports action photograph of ',
    tail: ', motion, energy, shallow depth of field, sharp focus, high detail, editorial sports photography',
    mods: ['golden-hour stadium light', 'bright midday sun', 'dramatic floodlights at night', 'moody overcast', 'sunset backlight', 'crisp winter light', 'vibrant arena glow', 'dusty sunlit haze', 'cool blue morning light', 'high-contrast spotlight', 'warm locker-room light', 'rain-soaked field light'],
    scenes: [
      'a basketball player dunking over a defender', 'a soccer striker bending a free kick', 'an american football running back breaking a tackle', 'a tennis player mid-serve on a clay court', 'a sprinter exploding out of the blocks', 'a swimmer diving into the pool', 'a cyclist leaning through a mountain switchback', 'a boxer landing a punch in the ring', 'a baseball batter connecting with a fastball', 'a golfer at the top of a powerful swing',
      'a skier carving through fresh powder', 'a surfer riding inside a barreling wave', 'a marathon crowd running across a city bridge', 'a gymnast mid-flip on the balance beam', 'a volleyball player spiking at the net', 'a rock climber reaching for a high hold', 'a hockey player firing a slapshot', 'a rugby scrum straining for the ball', 'a weightlifter locking out a heavy clean and jerk', 'a skateboarder catching air off a ramp',
      'a rowing eight pulling in perfect sync', 'a mountain biker launching off a jump', 'a figure skater in a spinning leap', 'a track cyclist banking high on a velodrome', 'a wrestler executing a takedown', 'a snowboarder grabbing air in a halfpipe', 'a cricket batsman driving through the covers', 'a fencer lunging with a foil', 'a martial artist mid flying kick', 'a beach volleyball dig in the sand',
      'a stadium packed with cheering fans under lights', 'a coach shouting instructions from the sideline', 'a triathlete transitioning from bike to run', 'a diver twisting off the ten-meter platform', 'a soccer goalkeeper flying for a save', 'a runner breaking the finish-line tape', 'a basketball crossover leaving a defender behind', 'a downhill skier tucking at high speed', 'a kayaker punching through whitewater rapids', 'a horse and jockey clearing a jump',
      'a young team huddled before a game', 'a tennis player celebrating match point', 'a football quarterback throwing a deep pass', 'a boxer training with a heavy bag', 'a sprinter crossing the line arms raised', 'a swimmer touching the wall to win', 'a cyclist peloton racing through a village', 'a basketball buzzer-beater falling through the net', 'a gymnast sticking a landing', 'a soccer team celebrating a goal',
      'a surfer paddling out at dawn', 'a climber silhouetted on a summit ridge', 'a runner training on a misty trail', 'a weight room athlete mid rep', 'a hockey goalie making a glove save', 'a golfer reading a putt on the green', 'a rugby player diving for a try', 'a skateboarder grinding a rail', 'a snow skier spraying powder', 'a track relay baton handoff',
    ],
  },
  {
    name: 'friends', upto: 3600,
    prompt: 'warm candid lifestyle photograph of ',
    tail: ', natural light, genuine emotion, film look, shallow depth of field, sharp focus, high detail',
    mods: ['golden-hour glow', 'bright airy daylight', 'cozy string-light evening', 'warm sunset backlight', 'soft overcast light', 'campfire glow', 'neon city night light', 'sunlit through windows', 'beach afternoon light', 'candlelit warmth', 'crisp autumn light', 'festival stage glow'],
    scenes: [
      'a group of friends laughing around a rooftop table at sunset', 'friends toasting drinks at a backyard barbecue', 'friends around a beach bonfire at night', 'a road-trip crew leaning out of a convertible', 'friends playing board games on a living-room floor', 'a group hiking and laughing on a mountain trail', 'friends sharing a picnic in a sunny park', 'friends cooking together in a bright kitchen', 'friends at a concert with hands in the air', 'friends huddled under blankets watching a movie',
      'friends taking a selfie on a city rooftop', 'a group cheering at a sports bar', 'friends paddling a canoe on a lake', 'friends dancing at a house party', 'a coffee-shop table of friends deep in conversation', 'friends toasting marshmallows over a campfire', 'a group biking together down a tree-lined street', 'friends jumping into a lake off a dock', 'friends decorating for a birthday party', 'friends playing guitar on a porch at dusk',
      'a group of friends at a farmers market', 'friends building a sandcastle at the beach', 'friends stargazing on a blanket', 'a group laughing over brunch on a patio', 'friends playing basketball at an outdoor court', 'friends walking through a city at night with neon signs', 'friends having a snowball fight', 'a group gathered around a food truck', 'friends kayaking together on a river', 'friends sharing headphones on a train',
      'friends at a rooftop pool party', 'a group toasting at a dinner table full of food', 'friends camping and cooking by a tent', 'friends laughing on a ferris wheel', 'a group painting together in a studio', 'friends playing cards late at night', 'friends walking dogs together in a park', 'a group watching fireworks from a hilltop', 'friends surfing and hanging out on the beach', 'friends carpooling and singing along to music',
      'friends gathered around a laptop laughing', 'a group at a bowling alley celebrating', 'friends sharing pizza on a fire escape', 'friends at a farmers-field music festival', 'a group hugging at an airport reunion', 'friends playing volleyball at the beach', 'friends roasting food at a tailgate', 'a group relaxing in a hammock grove', 'friends exploring a colorful street market', 'friends laughing in a diner booth',
      'a group toasting champagne on a boat', 'friends flying kites in an open field', 'friends warming hands at a winter market', 'a group playing video games on a couch', 'friends riding a rollercoaster', 'friends sketching together in a park', 'a group gathered at a beach sunset', 'friends baking cookies in a messy kitchen', 'friends laughing under umbrellas in the rain', 'a group gathered around a bonfire with guitars',
    ],
  },
  {
    name: 'inventors', upto: 4600,
    prompt: 'cinematic portrait photograph of an inventor, ',
    tail: ', workshop atmosphere, warm light, curious and brilliant mood, film look, sharp focus, high detail',
    mods: ['warm workshop tungsten light', 'dramatic single-lamp light', 'golden dusty sunbeam', 'cool blue lab glow', 'candlelit vintage warmth', 'bright maker-space daylight', 'moody chiaroscuro light', 'glowing invention light', 'soft window light', 'spark-lit forge glow', 'neon prototype glow', 'high-contrast rim light'],
    scenes: [
      'a wild-haired inventor surrounded by gears and blueprints', 'an inventor holding up a glowing new gadget', 'a young inventor soldering a circuit board at a cluttered bench', 'an inventor sketching designs on a chalkboard wall', 'an inventor in a garage lab full of contraptions', 'a Renaissance-style inventor with flying-machine sketches', 'an inventor testing a small robot on a workbench', 'an inventor with goggles amid sparks and tools', 'an inventor examining a prototype under a magnifier', 'an inventor at a 3D printer watching a part form',
      'an inventor with a lightbulb-moment expression', 'an inventor tinkering with a mechanical arm', 'an inventor surrounded by floating blueprints and gears', 'a woman inventor assembling a drone in her studio', 'an inventor in a steampunk workshop of brass machines', 'an inventor welding a metal frame with a mask up', 'an inventor testing a homemade rocket in a field', 'an inventor with a wall of tools and half-built machines', 'an inventor holding a glowing energy orb prototype', 'an inventor deep in thought before a wall of equations',
      'a child inventor building a robot from spare parts', 'an inventor unveiling a machine under a sheet', 'an inventor adjusting a giant clockwork mechanism', 'an inventor in a lab coat mixing glowing liquids', 'an inventor riding a strange self-built contraption', 'an inventor surrounded by drones mid-flight', 'an inventor at a drafting table late at night', 'an inventor with a jetpack prototype strapped on', 'an inventor repairing a vintage flying machine', 'an inventor presenting a hologram of an idea',
      'an elderly inventor in a workshop full of memories and machines', 'an inventor with wild ideas pinned across a corkboard', 'an inventor testing a wearable exosuit glove', 'an inventor in a barn workshop with sunlight streaming', 'an inventor tuning a homemade electric vehicle', 'an inventor with a telescope and star charts', 'an inventor building a wind-powered gadget on a rooftop', 'an inventor amid a workshop of automatons', 'an inventor sketching a bridge design at a big desk', 'an inventor smiling as a small machine comes to life',
      'an inventor in a maker space surrounded by tools', 'an inventor holding blueprints in a sunlit garage', 'an inventor with a spark of insight at a workbench', 'an inventor assembling a clockwork bird', 'an inventor testing a glowing battery cell', 'an inventor in a cluttered attic laboratory', 'an inventor with a robotic pet companion', 'an inventor examining a floating magnetic device', 'an inventor building a model rocket engine', 'an inventor surrounded by holographic schematics',
      'an inventor at a forge shaping a new tool', 'an inventor with a wall of vintage patents', 'an inventor testing a solar-powered contraption', 'an inventor tinkering under the hood of a strange vehicle', 'an inventor in goggles inspecting a glowing coil', 'an inventor building a walking robot in a barn', 'an inventor sketching wings for a flying suit', 'an inventor at a bench of blinking prototypes', 'an inventor presenting an invention to a small crowd', 'an inventor gazing proudly at a finished machine',
    ],
  },
  {
    name: 'boats', upto: 5600,
    prompt: 'cinematic photograph of ',
    tail: ', water reflections, dramatic sky, high detail, sharp focus, editorial marine photography',
    mods: ['golden-hour light on water', 'bright midday sun sparkling on the sea', 'dramatic stormy sky', 'calm sunset harbor light', 'misty morning light', 'crisp blue-sky day', 'moody overcast sea', 'warm marina evening light', 'tropical turquoise light', 'rich sunset backlight', 'foggy coastal light', 'high-contrast open-ocean light'],
    scenes: [
      'a sleek white luxury yacht cruising open water', 'a classic wooden sailboat heeling in the wind', 'a speedboat carving a sharp turn with spray', 'a fishing trawler returning to harbor at dawn', 'a tall ship under full sail on the ocean', 'a catamaran gliding over turquoise tropical water', 'a marina full of moored sailboats at sunset', 'a bass boat idling on a glassy lake at dawn', 'a canal boat drifting through a European town', 'a houseboat moored on a calm river',
      'a racing sailboat regatta with colorful spinnakers', 'a vintage runabout on a mountain lake', 'a superyacht anchored off a tropical island', 'a lobster boat hauling traps at sea', 'a rowboat on a mirror-still pond at dawn', 'a pontoon boat full of friends on a lake', 'a kayak gliding through a sea cave', 'a ferry crossing a misty bay', 'a tugboat guiding a cargo ship into port', 'a sailboat silhouetted against a fiery sunset',
      'a jet boat spraying a rooster tail of water', 'a wooden dinghy tied to a weathered dock', 'a cruise ship departing a harbor at dusk', 'a fleet of dragon boats racing', 'a gondola gliding down a Venetian canal', 'a deep-sea sportfishing boat battling a wave', 'a catamaran ferry speeding across a strait', 'a classic yacht with polished brass and teak', 'an inflatable dinghy skimming a calm cove', 'a schooner anchored in a quiet bay',
      'a powerboat leaping over ocean swells', 'a paddleboarder near a docked sailboat', 'a river barge loaded with cargo', 'a small sailboat in a bottle-blue lagoon', 'a fishing boat surrounded by seagulls', 'a luxury yacht deck with sunset views', 'a wooden canoe on a foggy northern lake', 'a racing hydroplane skimming the surface', 'a harbor of fishing boats under storm clouds', 'a sailboat cutting through whitecaps',
      'a marina boardwalk lined with yachts at night', 'a speedboat towing a water skier', 'a classic motor yacht in a calm harbor', 'a trawler net full of fish being hauled', 'a sailing yacht rounding a rocky headland', 'a pontoon at anchor for a lake picnic', 'a tall ship crew working the rigging', 'a fishing charter boat at golden hour', 'a catamaran anchored over a coral reef', 'a lone sailboat under a starry night sky',
    ],
  },
  {
    name: 'cars', upto: 6600,
    prompt: 'cinematic automotive photograph of ',
    tail: ', dramatic reflections, motion, high detail, sharp focus, editorial car photography',
    mods: ['golden-hour light', 'neon city night reflections', 'dramatic studio lighting', 'misty mountain-road light', 'bright desert sun', 'wet-road reflection light', 'sunset backlight', 'moody garage lighting', 'crisp morning light', 'high-contrast track light', 'warm coastal-highway light', 'foggy dawn light'],
    scenes: [
      'a Ferrari 488 GTB', 'a Lamborghini Huracan', 'a McLaren 720S', 'a Bugatti Chiron', 'a Porsche 911 GT3 RS', 'a Ferrari LaFerrari', 'a Lamborghini Aventador SVJ', 'a Koenigsegg Jesko', 'a McLaren P1', 'a Pagani Huayra',
      'a Chevrolet Corvette C8', 'a Nissan GT-R', 'an Audi R8', 'an Aston Martin Vantage', 'a Jaguar F-Type', 'a Lexus LC 500', 'a BMW M4', 'a Mercedes-AMG GT', 'a Porsche 718 Cayman GT4', 'a Toyota GR Supra',
      'a Mazda RX-7', 'a Honda NSX', 'a Subaru WRX STI', 'a Mitsubishi Lancer Evolution', 'a Nissan Silvia S15', 'a Toyota AE86 Trueno', 'a Honda Civic Type R', 'a Nissan 370Z', 'a Mazda MX-5 Miata', 'a Nissan Skyline R34 GT-R',
      'a Ford Mustang Shelby GT500', 'a Chevrolet Camaro ZL1', 'a Dodge Challenger SRT Hellcat', 'a Dodge Charger R/T', 'a 1967 Chevrolet Corvette Stingray', 'a Ford GT', 'a Pontiac Firebird Trans Am', 'a Plymouth Hemi Barracuda', 'a Chevrolet Chevelle SS 454', 'a Shelby Cobra 427',
      'a 1957 Chevrolet Bel Air', 'a Jaguar E-Type', 'a Mercedes-Benz 300SL Gullwing', 'a Porsche 356 Speedster', 'a Volkswagen Beetle', 'a Ford Model T', 'a Rolls-Royce Phantom', 'a Bentley Continental GT', 'an Aston Martin DB5', 'a Cadillac Eldorado',
      'a Tesla Model S Plaid', 'a Tesla Cybertruck', 'a Rivian R1T', 'a Porsche Taycan Turbo S', 'a Lucid Air', 'a Ford Mustang Mach-E', 'an Audi e-tron GT', 'a BMW i8', 'a Hyundai Ioniq 5', 'a Polestar 2',
      'a Ford F-150 Raptor', 'a Jeep Wrangler Rubicon', 'a Toyota Land Cruiser', 'a Land Rover Defender', 'a Ford Bronco', 'a Chevrolet Silverado', 'a Ram 1500 TRX', 'a Toyota Tacoma', 'a Mercedes-Benz G-Class G-Wagen', 'a Range Rover Sport',
    ],
  },
  {
    name: 'software', upto: 7600,
    prompt: 'cinematic photograph of ',
    tail: ', modern tech aesthetic, glowing accents, shallow depth of field, sharp focus, high detail',
    mods: ['cool blue tech glow', 'warm office daylight', 'moody dark-mode lighting', 'bright airy studio light', 'neon accent lighting', 'soft window light', 'dramatic monitor glow', 'clean minimalist light', 'purple-cyan gradient glow', 'golden-hour desk light', 'high-contrast key light', 'server-room aisle glow'],
    scenes: [
      'a developer coding at a glowing multi-monitor desk', 'a software team collaborating around a laptop', 'an abstract flowing stream of glowing code particles', 'a data center aisle of blinking server racks', 'a startup dev team at a whiteboard of flowcharts', 'a programmer working late lit by screen glow', 'a glowing network of connected nodes and lines', 'a hackathon room full of laptops and energy', 'a cloud-computing concept of floating servers', 'a mobile app designer sketching interface shapes',
      'a woman engineer debugging at a standing desk', 'an abstract 3D render of interlocking data blocks', 'a devops engineer monitoring glowing systems', 'a sleek laptop on a desk with soft bokeh lights', 'a futuristic holographic interface of glowing panels', 'a team celebrating a product launch in an office', 'an abstract circuit-board landscape glowing', 'a cybersecurity engineer at a dark workstation', 'a glowing globe wrapped in data connections', 'a coder wearing headphones in a cozy home office',
      'a swirl of binary light forming a tunnel', 'an open-plan software office with plants and screens', 'a developer pointing at a wall of sticky notes', 'a glowing keyboard in a dark room', 'a 3D data visualization of flowing particles', 'a pair of engineers reviewing code together', 'a futuristic control room of glowing displays', 'an abstract cloud made of glowing dots', 'a laptop with light streaming from the screen', 'a startup office with a foosball table and monitors',
      'an engineer soldering an IoT prototype', 'a glowing microchip on a circuit board macro', 'a team standup around a kanban board', 'a data scientist at a wall of charts', 'a futuristic server orb pulsing with light', 'a developer relaxing with coffee by a laptop', 'an abstract mesh of glowing geometric shapes', 'a QA engineer testing an app on many devices', 'a sleek workspace with dual monitors at dusk', 'a glowing fiber-optic burst of light',
      'a programmer at a rooftop cafe with a laptop', 'an abstract river of streaming code', 'a design team prototyping an app on a big screen', 'a glowing digital brain of connected nodes', 'a modern tech campus lobby at night', 'a developer high-fiving a teammate at a desk', 'a cloud data center exterior glowing at dusk', 'an engineer with AR glasses viewing holograms', 'a minimalist desk with a glowing laptop and plant', 'a swirling galaxy of glowing data points',
    ],
  },
  {
    name: 'ai', upto: 8600,
    prompt: 'cinematic futuristic digital art of ',
    tail: ', glowing, highly detailed, ethereal tech aesthetic, dramatic lighting, sharp focus, 8k',
    mods: ['glowing blue energy light', 'purple-cyan neon glow', 'ethereal white light', 'deep-space starlight', 'holographic shimmer', 'warm gold circuitry glow', 'dramatic volumetric rays', 'cool data-stream glow', 'high-contrast rim light', 'bioluminescent glow', 'electric pulse light', 'soft nebula haze'],
    scenes: [
      'a glowing artificial brain made of light and circuits', 'a humanoid AI face formed from flowing data', 'a translucent android awakening with glowing eyes', 'a vast neural network glowing in the dark', 'an AI assistant hologram floating over a desk', 'a robot and human touching fingertips with a spark', 'a glowing digital mind connected by fiber tendrils', 'a futuristic AI core pulsing at a data center heart', 'an android gazing at its own glowing hand', 'a swirling galaxy of interconnected data nodes',
      'a face dissolving into streams of glowing particles', 'a giant AI hologram towering over a city', 'a robot contemplating a glowing orb of knowledge', 'an abstract sculpture of flowing neural pathways', 'a cybernetic eye reflecting streams of code', 'an AI-generated dreamscape of impossible architecture', 'a glowing chip labeled as a synthetic brain macro', 'a humanoid robot meditating in a field of light', 'a hologram of a woman made of blue data', 'a futuristic lab growing a glowing AI mind',
      'a robot hand writing with a glowing pen', 'an ethereal AI goddess of light and circuitry', 'a network of glowing satellites around Earth', 'a digital phoenix rising from data streams', 'an android orchestra conducted by light', 'a glowing web of thoughts across a dark void', 'a futuristic android portrait with soft light', 'a mind uploading into a glowing cloud', 'a robot child discovering a glowing butterfly', 'an AI heart of pulsing golden circuitry',
      'a swirling vortex of machine-learning data', 'a humanoid AI standing in a temple of light', 'a glowing android surrounded by floating screens', 'a neural galaxy spiraling with light', 'an AI face emerging from a pool of liquid light', 'a robot gazing up at a sky of data streams', 'a crystalline AI core radiating energy', 'a futuristic android with a glowing spine', 'a hologram brain rotating above a table', 'a digital being formed of shifting geometry',
      'a robot reaching toward a glowing sun of data', 'an AI mind visualized as a luminous city', 'an android dreaming in a field of glowing flowers', 'a stream of consciousness rendered as light ribbons', 'a futuristic oracle of glowing screens', 'a robot and a child sharing a glowing hologram', 'a translucent AI figure walking through a server hall', 'a glowing constellation forming a face', 'a synthetic brain suspended in a glowing tank', 'an AI sunrise over a digital landscape',
    ],
  },
  {
    name: 'sales_training', upto: 9600,
    prompt: 'cinematic photograph of ',
    tail: ', energetic professional mood, warm light, shallow depth of field, sharp focus, high detail',
    mods: ['bright airy conference light', 'warm stage lighting', 'golden-hour office light', 'dramatic spotlight', 'clean modern daylight', 'moody seminar lighting', 'vibrant energetic light', 'soft window light', 'high-contrast keynote light', 'warm workshop light', 'uplifting sunrise light', 'cool professional light'],
    scenes: [
      'a sales trainer presenting at a whiteboard to a team', 'a motivational speaker energizing a conference crowd', 'a group of salespeople role-playing a pitch', 'a coach mentoring a young sales rep one on one', 'a sales team high-fiving after closing a deal', 'a seminar audience taking notes eagerly', 'a confident presenter with a headset mic on stage', 'a handshake sealing a business deal', 'a sales floor buzzing with reps on calls', 'a workshop of professionals brainstorming on sticky notes',
      'a trainer pointing to a growth chart on a screen', 'a diverse team celebrating hitting a target', 'a mentor coaching over coffee', 'a keynote speaker gesturing to a big audience', 'a small-group sales workshop around a table', 'a rep practicing a pitch in a mirror', 'a leader giving a pep talk to a huddled team', 'a professional shaking hands at a networking event', 'a trainer demonstrating a technique with props', 'a confident saleswoman presenting to executives',
      'a team applauding a colleague at a meeting', 'a coach drawing a strategy on a glass wall', 'a rep celebrating on a call with fists raised', 'a mentor and mentee reviewing a plan', 'a stage speaker walking through the crowd', 'a group of trainees laughing during a workshop', 'a leader awarding a top performer on stage', 'a sales bootcamp with people at laptops', 'a presenter energizing a room with a smile', 'a handshake with a city skyline behind',
      'a manager coaching a rep at a desk', 'a motivational poster moment of a team cheering', 'a professional confidently pitching to a boardroom', 'a workshop breakout group collaborating', 'a speaker with a wireless mic mid-gesture', 'a team fist-bump over a closed deal', 'a trainer high-energy in front of a whiteboard', 'a networking mixer of professionals talking', 'a mentor guiding a trainee through a script', 'a confident rep walking into an office building',
      'a coach clapping for a trainee breakthrough', 'a seminar hall filling with attendees', 'a rep celebrating a signed contract', 'a leader motivating a diverse sales team', 'a workshop wall of goals and metrics', 'a speaker receiving a standing ovation', 'a mentor and rep reviewing results on a tablet', 'a team stretching goals on a whiteboard', 'a professional confidently on a video sales call', 'a group cheering at a sales kickoff event',
    ],
  },
  {
    name: 'books', upto: 10600,
    prompt: 'cinematic warm photograph of ',
    tail: ', cozy literary mood, soft light, rich detail, shallow depth of field, sharp focus',
    mods: ['warm reading-lamp glow', 'soft window daylight', 'golden-hour library light', 'candlelit warmth', 'cozy fireplace glow', 'misty morning light', 'moody bookstore lighting', 'bright airy cafe light', 'dramatic single-lamp light', 'autumn afternoon light', 'magical glowing-book light', 'soft rainy-day light'],
    scenes: [
      'a cozy armchair reader beside a tall stack of books', 'an open book with pages glowing softly', 'a grand library with towering bookshelves', 'a person reading by a rainy window with tea', 'a charming bookstore aisle full of spines', 'a book club discussing around a coffee table', 'a reviewer writing notes beside an open book', 'a stack of well-worn books and reading glasses', 'a child reading under a blanket fort with a flashlight', 'an open book with a magical world rising from the pages',
      'a wall of colorful book spines floor to ceiling', 'a coffee cup resting on an open novel', 'a reader curled up in a window seat', 'a vintage desk with an open journal and quill', 'a sunlit reading nook overflowing with books', 'a hand turning a page in warm light', 'a spiral staircase in an old library', 'a bookshop cat asleep on a pile of books', 'a book open on a picnic blanket in a park', 'a glowing lantern beside a stack of classics',
      'a reviewer surrounded by highlighted books', 'an antique bookstore with ladders and lamps', 'a person reading on a cozy train journey', 'a stack of books with a steaming mug at dawn', 'a candlelit desk with an open leather book', 'a library reading room with green desk lamps', 'an open book releasing glowing letters into the air', 'a reader in a hammock with a paperback', 'a bookshelf wall with a rolling ladder', 'a book fair table piled with new releases',
      'a writer at a typewriter surrounded by books', 'a cozy fireside chair with a book and blanket', 'a stack of travel books and a globe', 'a bookshop window display at dusk', 'a reader lit by a single warm lamp at night', 'an open storybook with paper birds flying out', 'a university library at golden hour', 'a coffee shop reader among plants and books', 'a child in a bookstore reaching for a top shelf', 'a desk of open reference books and notes',
      'a leather-bound book collection on oak shelves', 'a reader on a bench under autumn leaves', 'a glowing e-reader beside a stack of hardcovers', 'a book review desk with pen and open novel', 'a cozy attic library with a round window', 'an open cookbook in a warm kitchen', 'a bookmark tucked into a thick classic', 'a bookstore reading corner with soft chairs', 'a stack of books forming a spiral tower', 'a reader beside a window overlooking the rain',
    ],
  },
  {
    name: 'current_events', upto: 11600,
    prompt: 'cinematic photojournalism photograph of ',
    tail: ', documentary realism, dramatic light, sharp focus, high detail, editorial news photography',
    mods: ['dramatic overcast light', 'golden-hour city light', 'harsh midday sun', 'moody dusk light', 'bright newsroom light', 'stormy sky light', 'neon night-city light', 'crisp morning light', 'high-contrast spotlight', 'warm sunset backlight', 'foggy street light', 'rain-soaked reflections'],
    scenes: [
      'a modern newsroom with journalists at work', 'a reporter speaking into a microphone on a city street', 'a large peaceful crowd gathered in a public square', 'a press conference with cameras raised', 'a globe surrounded by news headlines of light', 'a busy city intersection at rush hour', 'a satellite dish news van at dusk', 'a photojournalist raising a camera in a crowd', 'a wall of glowing news screens', 'a stock exchange floor in motion',
      'a city skyline under dramatic storm clouds', 'a marathon of commuters crossing a bridge', 'a night rally lit by phone lights', 'a broadcast anchor desk under studio lights', 'a documentary crew filming in a city', 'a world map with glowing connection lines', 'a crowded train platform at rush hour', 'a bustling open-air market', 'a harbor with cargo ships and cranes', 'a wind farm turning under a big sky',
      'a solar field stretching to the horizon', 'a city protest with colorful signs at a distance', 'a relief-supply distribution scene', 'a floodlit sports stadium event', 'a busy airport terminal at dawn', 'a data-driven election-night graphics wall of light', 'a construction boom skyline with cranes', 'a farmers field at harvest under a wide sky', 'a coastal city bracing for a storm', 'a bright modern hospital exterior',
    ],
  },
  {
    name: 'gaming', upto: 12600,
    prompt: 'cinematic vibrant photograph of ',
    tail: ', RGB glow, energetic mood, high detail, sharp focus, gaming aesthetic',
    mods: ['RGB neon glow', 'purple-blue gamer lighting', 'dramatic arena spotlights', 'moody dark-room screen glow', 'vibrant LED light', 'neon night light', 'high-contrast esports light', 'cool blue monitor glow', 'colorful stage lighting', 'warm cozy setup light', 'electric pulse light', 'holographic shimmer'],
    scenes: [
      'a pro gamer at an RGB-lit battlestation', 'an esports arena packed with cheering fans', 'a close-up of hands on a glowing mechanical keyboard', 'a streamer at a neon-lit setup with a mic', 'a retro arcade glowing with cabinets', 'a VR gamer reaching into a virtual world', 'a LAN party of gamers at glowing rigs', 'an esports team celebrating a win on stage', 'a controller resting on a glowing desk', 'a gaming cafe full of glowing monitors',
      'a tournament stage with giant screens', 'a cozy gaming setup with LED strips at night', 'a first-person view of a neon racing game', 'a crowd watching a giant esports screen', 'a gamer with a headset mid-intense match', 'a shelf of glowing collectible figures', 'a fighting-game arcade duel', 'a battlestation with triple monitors and neon', 'a VR arena with players in headsets', 'a glowing console setup in a dark room',
      'a pro team huddle before a match', 'a claw-machine arcade lit in neon', 'a gamer celebrating with arms raised', 'a mobile gamer lit by phone glow at night', 'a retro pixel-art city of neon light', 'a keyboard and mouse in dramatic RGB light', 'a cosplay gamer at a convention', 'an esports caster desk under studio lights', 'a glowing racing-sim cockpit rig', 'a crowd of fans with glowing wristbands',
    ],
  },
  {
    name: 'nightclubs', upto: 13600,
    prompt: 'cinematic vibrant photograph of ',
    tail: ', dynamic energy, glowing lights, shallow depth of field, sharp focus, nightlife aesthetic',
    mods: ['laser-light show glow', 'neon pink and blue light', 'strobe-lit energy', 'moody smoky lighting', 'golden VIP glow', 'ultraviolet glow', 'colorful stage lights', 'dramatic spotlight beams', 'deep-red club light', 'electric blue haze', 'disco-ball sparkle', 'high-contrast silhouette light'],
    scenes: [
      'a DJ mixing at a booth above a packed dance floor', 'a crowd with hands up under laser lights', 'a neon-lit club entrance at night', 'silhouettes dancing in colored smoke', 'a VIP bottle-service table with sparklers', 'a bartender pouring cocktails under neon', 'a disco ball scattering light over dancers', 'a rooftop club with a city skyline view', 'a crowd bathed in ultraviolet glow', 'a DJ silhouetted against a wall of light',
      'a dance floor lit by sweeping spotlights', 'a neon cocktail glowing on a bar', 'a packed club under strobe lights', 'a glowing dance cage with a performer', 'a smoky lounge with velvet seating', 'a crowd cheering as confetti falls', 'a bar lined with glowing bottles', 'a couple dancing in colorful light', 'a club hallway lit with neon signs', 'a stage performer with pyrotechnics',
      'a rooftop pool party at night with lights', 'a DJ drop moment with hands in the air', 'a neon-lit staircase into a club', 'a crowd silhouette against a bright stage', 'a glowing dance floor grid', 'a bartender flair-pouring under spotlights', 'a lounge of glowing low tables', 'a club balcony overlooking the dance floor', 'a laser tunnel over a crowd', 'a late-night city club exterior in the rain',
    ],
  },
  {
    name: 'estates', upto: 14600,
    prompt: 'cinematic architectural photograph of ',
    tail: ', luxury real-estate aesthetic, dramatic light, high detail, sharp focus',
    mods: ['golden-hour glow', 'bright blue-sky day', 'twilight exterior light', 'warm interior lamp light', 'dramatic sunset backlight', 'misty morning light', 'crisp midday light', 'moody dusk light', 'poolside reflection light', 'soft overcast light', 'grand entrance light', 'high-contrast architectural light'],
    scenes: [
      'a sprawling modern mansion with an infinity pool', 'a grand estate with manicured gardens', 'a Mediterranean villa at golden hour', 'a glass mansion glowing at twilight', 'a hilltop estate overlooking the ocean', 'a palatial marble entrance hall', 'a gated driveway lined with palm trees', 'a luxury estate pool deck at sunset', 'a countryside manor with sweeping lawns', 'a modern cliffside home with ocean views',
      'a grand chandelier foyer of a mansion', 'a lakeside estate with a private dock', 'a rooftop terrace of a luxury penthouse', 'a colonial estate with white columns', 'a desert modernist villa at dusk', 'an estate wine cellar with stone arches', 'a grand staircase in a luxury home', 'a mansion at night glowing warmly', 'a garden fountain before a stately home', 'a mountain chalet estate in the snow',
      'a sleek minimalist mansion by a reflecting pool', 'a vineyard estate at golden hour', 'a coastal estate with a glass wall to the sea', 'a luxury home theater room', 'a grand library room of a mansion', 'a private tennis court beside an estate', 'a sunlit atrium of a luxury home', 'a manor gatehouse at dawn', 'a lavish master suite with a view', 'a sprawling estate aerial at sunset',
    ],
  },
  {
    name: 'neighborhoods', upto: 15600,
    prompt: 'cinematic photograph of ',
    tail: ', warm community feel, natural light, high detail, sharp focus',
    mods: ['golden-hour glow', 'bright spring daylight', 'warm autumn light', 'cozy evening porch light', 'misty morning light', 'crisp blue-sky day', 'soft overcast light', 'sunset backlight', 'snowy winter light', 'string-light evening', 'dappled tree-shade light', 'twilight streetlamp glow'],
    scenes: [
      'a tree-lined suburban street at golden hour', 'a row of colorful brownstones in a city', 'a cozy cul-de-sac of family homes', 'a small-town main street with shops', 'a friendly neighborhood block party', 'a craftsman house with a welcoming porch', 'kids playing in a leafy neighborhood park', 'a quiet street after fresh snow', 'a coastal town of pastel cottages', 'a historic district of charming row houses',
      'a farmers market on a neighborhood corner', 'a bike ride down a quiet residential lane', 'a garden-lined sidewalk in spring bloom', 'a community garden between houses', 'a walkable downtown with cafe patios', 'a suburban aerial of winding streets', 'a neighbor watering flowers on a porch', 'a mountain-town street with cozy homes', 'a lakeside community of cabins', 'a golden-hour view over rooftops',
      'a leafy park with a playground and benches', 'a neighborhood coffee shop corner', 'a friendly dog walk on a shaded street', 'a holiday-lit residential street at dusk', 'a small-town square with a fountain', 'a row of townhomes with bright doors', 'a suburban backyard barbecue gathering', 'a quiet street with autumn leaves falling', 'a bakery on a cobblestone corner', 'a community mural on a neighborhood wall',
    ],
  },
  {
    name: 'life', upto: 16600,
    prompt: 'cinematic heartfelt photograph of ',
    tail: ', genuine emotion, warm natural light, film look, shallow depth of field, sharp focus',
    mods: ['golden-hour glow', 'soft morning light', 'warm sunset backlight', 'bright hopeful daylight', 'cozy candlelit warmth', 'misty dawn light', 'dappled sunlight', 'gentle overcast light', 'string-light evening', 'sunrise over hills', 'warm window light', 'high-contrast emotive light'],
    scenes: [
      'a family watching a sunrise together on a hill', 'a newborn baby holding an adult finger', 'an elderly couple walking hand in hand', 'a child chasing bubbles in a sunny yard', 'a couple dancing in a warm kitchen', 'friends laughing around a dinner table', 'a graduate tossing a cap into the sky', 'a parent teaching a child to ride a bike', 'a quiet moment of coffee at sunrise', 'a person standing atop a mountain at dawn',
      'a family picnic under a big tree', 'a couple watching the stars from a blanket', 'a grandmother and grandchild baking together', 'a runner greeting the sunrise on a trail', 'a wedding embrace at golden hour', 'a child blowing out birthday candles', 'a hand planting a seedling in soil', 'a quiet reader by a rainy window', 'a father carrying a child on his shoulders', 'friends jumping into a lake in summer',
      'a couple on a road trip at sunset', 'a mother and baby in soft morning light', 'a group hug of reunited friends', 'a lone figure watching waves at dusk', 'a family decorating a home for the holidays', 'a child reaching for a butterfly', 'an elderly artist painting in a garden', 'a couple sharing an umbrella in the rain', 'a sunrise yoga session by the sea', 'a candlelit family dinner full of laughter',
    ],
  },
  {
    name: 'franchises', upto: 17600,
    prompt: 'cinematic photograph of ',
    tail: ', bright commercial appeal, clean modern look, high detail, sharp focus',
    mods: ['bright midday light', 'golden-hour storefront glow', 'warm interior light', 'neon sign glow at dusk', 'clean daylight', 'vibrant sunny light', 'moody evening light', 'crisp morning light', 'high-contrast retail light', 'warm cafe light', 'drive-thru night light', 'grand-opening festive light'],
    scenes: [
      'a bustling fast-food restaurant at lunchtime', 'a bright coffee-shop franchise counter', 'a busy drive-thru lane at dusk', 'a gleaming retail franchise storefront', 'a modern gym franchise interior', 'a franchise grand-opening ribbon cutting', 'a smiling franchise owner in their shop', 'a fast-casual restaurant dining room', 'a smoothie bar with fresh fruit displays', 'a franchise bakery with a full display case',
      'a burger joint kitchen in full swing', 'a pizza franchise oven with fresh pies', 'a car-wash franchise at golden hour', 'a convenience store franchise interior', 'a bright ice-cream shop with a queue', 'a taco franchise counter with fresh food', 'a franchise bookstore-cafe interior', 'a pet-store franchise aisle', 'a salon franchise with styling stations', 'a sandwich shop with staff making orders',
      'a franchise storefront strip mall at dusk', 'a busy food-court franchise stall', 'a juice bar with bright signage-free counter', 'a franchise donut shop display', 'a modern quick-service kitchen line', 'a franchise cafe patio with customers', 'a gym franchise reception desk', 'a fresh-salad franchise counter', 'a franchise coffee roaster interior', 'a grand-opening crowd outside a new shop',
    ],
  },
  {
    name: 'school', upto: 18600,
    prompt: 'cinematic photograph of ',
    tail: ', warm educational mood, natural light, high detail, sharp focus',
    mods: ['bright classroom daylight', 'golden-hour campus light', 'warm library light', 'soft window light', 'crisp autumn campus light', 'cheerful morning light', 'moody study-hall light', 'dramatic auditorium light', 'sunny playground light', 'cozy reading light', 'graduation-day light', 'high-contrast lecture light'],
    scenes: [
      'a bright classroom of engaged students', 'a university campus quad at golden hour', 'graduates tossing caps into the air', 'a lecture hall filling with students', 'kids raising hands in an elementary class', 'a science lab with students at experiments', 'a cozy library study nook of students', 'a yellow school bus on a tree-lined road', 'a playground full of children at recess', 'a teacher writing on a chalkboard',
      'students collaborating around a table', 'a campus library reading room', 'a chemistry class with beakers and goggles', 'a music classroom with instruments', 'an art class with easels and paint', 'a computer lab of students coding', 'a gymnasium during a school assembly', 'a professor lecturing to a full hall', 'a student walking a leafy campus path', 'a kindergarten circle-time story',
      'a graduation ceremony on a sunny lawn', 'a study group in a coffee-shop corner', 'a school hallway lined with lockers', 'a robotics club testing a machine', 'a debate team at a podium', 'a campus at sunset with warm windows', 'a teacher helping a student one on one', 'a school science-fair display', 'students reading under a big oak tree', 'a bright preschool classroom of toys and books',
    ],
  },
  {
    name: 'aquariums', upto: 19600,
    prompt: 'cinematic vibrant underwater photograph of ',
    tail: ', rich color, glowing water, high detail, sharp focus, aquarium aesthetic',
    mods: ['glowing blue aquarium light', 'vibrant reef color', 'soft backlit water', 'dramatic beam of light through water', 'bioluminescent glow', 'warm planted-tank light', 'cool deep-water light', 'colorful coral glow', 'moody dark-water light', 'sunlit shallow reef', 'neon jellyfish glow', 'high-contrast tank light'],
    scenes: [
      'a vibrant coral reef aquarium full of fish', 'a school of clownfish in a sea anemone', 'a glowing jellyfish tank in a dark room', 'a lush planted freshwater aquascape', 'a public aquarium tunnel with sharks overhead', 'a betta fish with flowing fins', 'a reef tank with purple and orange corals', 'a seahorse among swaying sea grass', 'a giant kelp forest tank with light beams', 'a nano aquarium with tiny shrimp and plants',
      'a moray eel peeking from a reef', 'a tank of neon tetras schooling', 'a sea turtle gliding in a big aquarium', 'a colorful saltwater reef at feeding time', 'an aquascaped tank with driftwood and moss', 'a ray gliding over a sandy tank floor', 'a discus fish pair in a planted tank', 'a glowing moon jellyfish cluster', 'a nano reef with a clownfish and coral', 'a freshwater tank with angelfish',
      'an aquarium storefront glowing with tanks', 'a diver cleaning a huge public aquarium', 'a pufferfish among bright corals', 'a tank of glowing GloFish in the dark', 'a reef aquarium with anemones and shrimp', 'a planted tank with a school of rasboras', 'a lionfish drifting over a reef', 'a cichlid tank with rocky caves', 'a shrimp tank close-up with moss', 'a serene aquascape lit at golden hour',
    ],
  },
  {
    name: 'pets', upto: 20600,
    prompt: 'cinematic heartwarming photograph of ',
    tail: ', adorable, natural light, shallow depth of field, sharp focus, high detail',
    mods: ['golden-hour glow', 'bright airy daylight', 'cozy indoor light', 'warm window light', 'soft overcast light', 'sunny backyard light', 'playful park light', 'gentle morning light', 'warm fireside light', 'sunset backlight', 'dappled tree-shade light', 'high-contrast portrait light'],
    scenes: [
      'a golden retriever puppy in a sunny yard', 'a fluffy cat curled on a windowsill', 'a happy dog catching a frisbee mid-air', 'a kitten playing with a ball of yarn', 'a dog and owner hiking a mountain trail', 'a corgi running through autumn leaves', 'a cat stretching in a warm sunbeam', 'a puppy peeking out of a picnic basket', 'a dog with its head out a car window', 'a bunny nibbling clover in a garden',
      'a parrot with vivid feathers on a perch', 'a dog splashing in ocean waves', 'a cat and dog cuddling on a couch', 'a hamster stuffing its cheeks', 'a horse nuzzling a child over a fence', 'a group of puppies in a basket', 'a cat batting at falling snow', 'a dog wearing goggles on a road trip', 'a guinea pig munching a strawberry', 'a dog leaping into a lake off a dock',
      'a sleepy kitten in cupped hands', 'a dog and owner at a sunset beach', 'a fluffy cat in a cozy blanket fort', 'a puppy learning to sit in a park', 'a bearded dragon basking under a lamp', 'a dog surrounded by autumn pumpkins', 'a cat perched on a bookshelf', 'a golden puppy with big curious eyes', 'a dog running on a spring meadow', 'a pair of kittens tumbling in play',
    ],
  },
  {
    name: 'telecom', upto: 21600,
    prompt: 'cinematic photograph of ',
    tail: ', modern connectivity aesthetic, glowing accents, dramatic light, sharp focus, high detail',
    mods: ['cool blue tech glow', 'golden-hour sky light', 'dramatic sunset light', 'neon data glow', 'crisp blue-sky day', 'moody dusk light', 'glowing network light', 'high-contrast tower light', 'starlit night sky', 'warm control-room light', 'electric pulse light', 'foggy dawn light'],
    scenes: [
      'a cell tower silhouetted against a sunset sky', 'a technician working atop a communications tower', 'glowing fiber-optic cables bursting with light', 'a satellite orbiting Earth with beaming signals', 'a data center aisle of glowing servers', 'a city skyline wrapped in glowing network lines', 'a 5G antenna array against a blue sky', 'a network operations center with glowing maps', 'a hand holding a phone with glowing connection arcs', 'an undersea cable glowing across the ocean floor',
      'a satellite dish farm at golden hour', 'a glowing globe connected by data streams', 'a lineman splicing fiber in a street vault', 'a rooftop of microwave communication dishes', 'a futuristic city with beaming signal towers', 'a bundle of glowing fiber strands macro', 'a control room of network engineers', 'a mountain-top relay tower at dawn', 'a glowing map of global connections', 'a technician testing a fiber line with light',
      'a starlink-style satellite constellation over Earth', 'a phone tower crew at sunrise', 'a glowing router with light trails', 'a server room with blue LED racks', 'a city at night pulsing with data light', 'a fiber trench being laid along a road', 'a signal wave rippling across a landscape', 'a communications van with a raised mast', 'a glowing network node hub', 'a technician on a ladder at a junction box',
    ],
  },
  {
    name: 'wellness', upto: 22600,
    prompt: 'cinematic serene photograph of ',
    tail: ', calm uplifting mood, soft natural light, high detail, sharp focus, wellness aesthetic',
    mods: ['soft morning light', 'golden-hour glow', 'calm spa lighting', 'misty dawn light', 'bright airy daylight', 'warm candlelit glow', 'sunlit studio light', 'gentle overcast light', 'sunrise-over-water light', 'cozy warm light', 'dappled forest light', 'high-contrast calm light'],
    scenes: [
      'a woman doing yoga at sunrise on a cliff', 'a peaceful meditation in a quiet studio', 'a spa scene with candles and stones', 'a colorful healthy smoothie bowl', 'a runner stretching at dawn by the sea', 'a person doing tai chi in a misty park', 'a relaxing hot-spring bath in nature', 'a bright bowl of fresh salad ingredients', 'a person journaling with tea by a window', 'a group yoga class in a sunlit studio',
      'a massage therapy session in a calm room', 'a sunrise beach meditation pose', 'a bowl of colorful fruit and granola', 'a hiker breathing deep on a mountain summit', 'a cozy self-care bath with flowers', 'a person stretching on a yoga mat at home', 'a mindfulness walk in an autumn forest', 'a green juice and vegetables on a counter', 'a peaceful zen rock garden', 'a woman meditating by a calm lake',
      'a spa reflexology foot massage', 'a sunrise stretch on a rooftop', 'a herbal tea and open journal', 'a forest-bathing walk among tall trees', 'a wellness retreat pavilion at dawn', 'a person doing breathwork by the ocean', 'a bright kitchen preparing healthy food', 'a sound-bath with singing bowls', 'a serene infinity pool at sunrise', 'a yoga tree pose silhouetted at sunset',
    ],
  },
  {
    name: 'skill_drills', upto: 23600,
    prompt: 'dynamic cinematic photograph of ',
    tail: ', focused practice energy, motion, high detail, sharp focus, training aesthetic',
    mods: ['bright gym light', 'golden-hour field light', 'dramatic spotlight', 'moody training-room light', 'crisp morning light', 'vibrant court light', 'high-contrast action light', 'warm studio light', 'floodlit night practice', 'cool focused light', 'sunlit practice light', 'energetic rim light'],
    scenes: [
      'a basketball player running dribbling drills with cones', 'a soccer player practicing footwork through markers', 'a pianist practicing scales with focus', 'a boxer drilling combinations on pads', 'a dancer rehearsing a move at a mirror', 'a tennis player hitting a wall of practice serves', 'a coder practicing at a keyboard with focus', 'a golfer drilling putts on a practice green', 'a martial artist repeating a kata', 'a quarterback throwing at target nets',
      'a violinist practicing bowing technique', 'a sprinter doing ladder agility drills', 'a swimmer drilling stroke technique', 'a chef practicing knife skills', 'a drummer practicing rudiments', 'a climber drilling on a bouldering wall', 'a batter taking swings in a batting cage', 'a dancer stretching at a ballet barre', 'a goalkeeper drilling reaction saves', 'a calligrapher practicing strokes',
      'a skateboarder repeating a trick at a park', 'a hockey player drilling stick handling', 'a singer practicing scales in a booth', 'a gymnast drilling on the balance beam', 'a runner doing hill-sprint repeats', 'a guitarist practicing finger exercises', 'a volleyball player drilling serves', 'a fencer practicing lunges', 'a rower drilling form on an erg', 'a young athlete practicing free throws at dusk',
    ],
  },
  {
    name: 'travel', upto: 24600,
    prompt: 'cinematic travel photograph of ',
    tail: ', wanderlust mood, dramatic light, vivid color, high detail, sharp focus',
    mods: ['golden-hour glow', 'bright tropical light', 'dramatic sunset light', 'misty mountain light', 'vibrant midday sun', 'blue-hour city light', 'warm desert light', 'crisp alpine light', 'neon night-city light', 'soft coastal light', 'starry night sky', 'high-contrast landscape light'],
    scenes: [
      'a turquoise tropical beach with palm trees', 'a backpacker overlooking a mountain valley', 'a historic European old-town square', 'a hot-air balloon over a desert at dawn', 'a bustling Asian night market with lanterns', 'a lone road winding through red desert canyons', 'a couple watching a city sunset from a rooftop', 'a snowy alpine village at golden hour', 'a Greek island of white-and-blue houses', 'a train winding along a coastal cliff',
      'a camel caravan over sand dunes at sunset', 'a waterfall in a lush jungle', 'a gondola on a Venice canal at dusk', 'a temple among misty mountains at sunrise', 'a beach hut over turquoise water', 'a road trip convertible on a coastal highway', 'a northern-lights sky over a cabin', 'a vibrant spice market in a old city', 'a cliffside monastery above the clouds', 'a lantern-lit river festival at night',
      'a hiker on a ridge above the clouds', 'a tropical overwater bungalow at sunset', 'a cobblestone alley with cafe tables', 'a lighthouse on a rugged coast at dusk', 'a desert oasis with palm trees', 'a mountain lake reflecting snowy peaks', 'a bustling harbor of colorful boats', 'a rice-terrace valley at golden hour', 'a city skyline at blue hour from a bridge', 'a starry night over a desert camp',
    ],
  },
  {
    name: 'money', upto: 25600,
    prompt: 'cinematic photograph of ',
    tail: ', wealth and finance aesthetic, dramatic light, glowing accents, high detail, sharp focus',
    mods: ['golden luxury light', 'dramatic dark studio light', 'bright clean daylight', 'warm gold glow', 'high-contrast spotlight', 'cool blue finance light', 'sunset skyline light', 'moody vault lighting', 'glowing green growth light', 'rich amber light', 'neon market glow', 'crisp editorial light'],
    scenes: [
      'a stack of gold coins glowing warmly', 'a rising staircase of golden coins', 'a growing plant sprouting from a jar of coins', 'a glowing upward financial growth arrow of light', 'a bull statue before a skyline at sunset', 'hands exchanging a golden coin', 'a vault of gleaming gold bars', 'a piggy bank on a sunlit windowsill', 'a city financial district at golden hour', 'a glowing globe surrounded by currency symbols of light',
      'a person planting a coin like a seed', 'a soaring skyline of glass banking towers', 'a golden key on a stack of coins', 'an abstract river of glowing gold light', 'a hand dropping a coin into a jar', 'a mountain of gold coins with light rays', 'a sleek modern bank interior', 'a glowing candlestick market chart of light', 'a treasure chest overflowing with gold', 'a sunrise over a prosperous city skyline',
      'a golden compass on a wealth journey map', 'a bright green sprout growing through coins', 'a luxury handshake over a gleaming desk', 'a fan of gold coins catching light', 'a rocket of light rising over a skyline', 'a glowing safe door opening with light', 'a bull and skyline in dramatic light', 'a golden hourglass beside coins', 'an abstract upward staircase of light', 'a prosperous harbor of trade at sunset',
    ],
  },
  {
    name: 'dining', upto: 26600, prompt: 'cinematic mouthwatering photograph of ',
    tail: ', warm restaurant ambiance, rich color, shallow depth of field, sharp focus, food photography',
    mods: ['warm candlelit glow', 'golden-hour restaurant light', 'bright airy brunch light', 'moody fine-dining light', 'cozy bistro light', 'soft window light', 'dramatic plating spotlight', 'warm string-light patio', 'rich sunset dinner light', 'clean editorial light', 'rustic kitchen light', 'elegant tablescape light'],
    scenes: [
      'an elegant fine-dining plated dish', 'a candlelit dinner table set for two', 'a lavish dinner party spread on a long table', 'a chef plating at a chef\'s table', 'a rustic farm-to-table feast outdoors', 'a colorful brunch spread with coffee', 'a sizzling steak on a cast-iron plate', 'a sushi platter beautifully arranged', 'a cozy Italian trattoria dinner', 'a festive holiday dinner table',
      'a wine-pairing dinner in a cellar', 'a rooftop dinner with a city view', 'a colorful tapas spread on a table', 'a decadent dessert plated with sauce', 'a family passing dishes at dinner', 'a seafood tower on ice', 'a candlelit anniversary dinner', 'a bustling open kitchen dining room', 'a picnic charcuterie board in a park', 'a beach dinner table at sunset',
    ],
  },
  {
    name: 'events', upto: 27600, prompt: 'cinematic photograph of ',
    tail: ', vibrant atmosphere, dramatic light, high detail, sharp focus, event photography',
    mods: ['dramatic stage lighting', 'golden-hour outdoor light', 'sparkling gala light', 'colorful festival light', 'bright convention light', 'moody concert light', 'warm celebration glow', 'neon night-event light', 'spotlight beams', 'confetti-filled light', 'elegant chandelier light', 'high-energy crowd light'],
    scenes: [
      'a packed conference keynote hall', 'an elegant black-tie gala', 'a crowd at an outdoor music festival', 'an awards ceremony on a bright stage', 'a bustling trade-show floor', 'a concert crowd with hands raised', 'a corporate networking mixer', 'a fireworks finale over a crowd', 'a wedding reception under string lights', 'a product launch on a glowing stage',
      'a charity fundraiser dinner', 'a stadium event with a roaring crowd', 'a festival stage at golden hour', 'a red-carpet arrival scene', 'a conference expo with booths', 'a rooftop launch party', 'a graduation ceremony crowd', 'a street festival with food stalls', 'a gala ballroom with round tables', 'a celebration with confetti cannons',
    ],
  },
  {
    name: 'gatherings', upto: 28600, prompt: 'cinematic warm photograph of ',
    tail: ', joyful togetherness, natural light, shallow depth of field, sharp focus',
    mods: ['golden-hour glow', 'warm string-light evening', 'bright backyard daylight', 'cozy indoor light', 'sunset backlight', 'campfire glow', 'festive candlelight', 'soft overcast light', 'warm porch light', 'lantern-lit evening', 'sunny picnic light', 'holiday hearth glow'],
    scenes: [
      'a big family reunion in a backyard', 'a group toasting at a celebration dinner', 'a community potluck on long tables', 'a birthday party with balloons and cake', 'a backyard barbecue with friends and family', 'a holiday gathering around a fireplace', 'a picnic reunion in a sunny park', 'a rooftop gathering at golden hour', 'a bonfire gathering with guitars', 'a garden party with lanterns',
      'a friendsgiving dinner table', 'a block party on a neighborhood street', 'a beach gathering at sunset', 'a game-night gathering around a table', 'a housewarming party in a bright home', 'a multigenerational holiday dinner', 'a lakeside family gathering', 'a farmhouse harvest gathering', 'a cozy cabin gathering in winter', 'a celebration toast with sparklers',
    ],
  },
  {
    name: 'holidays', upto: 29600, prompt: 'cinematic festive photograph of ',
    tail: ', warm holiday magic, glowing lights, rich color, sharp focus, high detail',
    mods: ['warm christmas-light glow', 'cozy fireplace warmth', 'sparkling festive light', 'snowy blue-hour light', 'golden candlelight', 'colorful fireworks light', 'twinkling string lights', 'soft winter morning light', 'autumn harvest light', 'spooky moonlit glow', 'bright spring light', 'magical glowing light'],
    scenes: [
      'a decorated Christmas tree glowing by a fireplace', 'a festive holiday dinner table with candles', 'New Year fireworks over a city skyline', 'a cozy cabin in fresh snow with warm windows', 'a Thanksgiving feast with a golden turkey', 'a carved pumpkin porch on a misty Halloween night', 'a wreath on a snowy front door', 'children opening gifts on Christmas morning', 'a menorah glowing with candles', 'a spring holiday table with fresh flowers',
      'a fireplace mantel with stockings and lights', 'a sparkler celebration on New Year\'s Eve', 'a snowy village square with holiday lights', 'a festive market with warm lanterns', 'an autumn harvest table with pumpkins', 'a family decorating a Christmas tree', 'a glowing jack-o-lantern display', 'a warm holiday hearth with garland', 'fireworks reflected over a harbor', 'a cozy holiday morning with cocoa and lights',
    ],
  },
  {
    name: 'media', upto: 30600, prompt: 'cinematic photograph of ',
    tail: ', creative production mood, dramatic light, high detail, sharp focus',
    mods: ['dramatic studio lighting', 'warm set light', 'neon night light', 'moody production light', 'bright softbox light', 'colorful stage light', 'cinematic key light', 'cool blue screen glow', 'spotlight beams', 'golden-hour set light', 'high-contrast light', 'glowing edit-suite light'],
    scenes: [
      'a film set with cameras and lighting rigs', 'a podcast studio with microphones and headphones', 'a broadcast news set under studio lights', 'a photographer directing a studio shoot', 'a video editor at a glowing multi-screen suite', 'a musician recording in a studio booth', 'a live-stream setup with ring lights', 'a director watching a monitor on set', 'a boom operator on a film shoot', 'a bustling newsroom of journalists',
      'a concert being filmed by a camera crew', 'a green-screen production stage', 'a radio host at a mixing board', 'a documentary crew filming outdoors', 'a color-grading suite glowing at night', 'a photo studio with backdrops and lights', 'a sound engineer at a large mixing console', 'a talk-show set with bright lights', 'a drone operator filming a landscape', 'a magazine photo shoot in progress',
    ],
  },
  {
    name: 'speeches', upto: 31600, prompt: 'cinematic photograph of ',
    tail: ', inspiring commanding mood, dramatic light, high detail, sharp focus',
    mods: ['dramatic stage spotlight', 'warm auditorium light', 'bright keynote light', 'moody single-spotlight', 'golden-hour outdoor light', 'grand hall light', 'high-contrast podium light', 'soft uplifting light', 'crowd-lit ambiance', 'cinematic key light', 'sunrise inspiration light', 'elegant chandelier light'],
    scenes: [
      'a speaker at a podium before a large audience', 'a keynote presenter walking a bright stage', 'a TED-style talk with a single spotlight', 'a graduation commencement speech', 'a leader addressing a crowd outdoors', 'a motivational speaker gesturing on stage', 'a speaker receiving a standing ovation', 'a panel discussion under stage lights', 'a woman giving a confident keynote', 'a speaker silhouetted before a giant screen',
      'a commencement speaker at a podium', 'a business leader addressing a conference', 'a speaker on a grand hall stage', 'a coach giving a locker-room pep talk', 'a speaker at a rally with a microphone', 'a founder pitching on a startup stage', 'a speaker gesturing to an engaged crowd', 'an award acceptance speech at a mic', 'a professor lecturing to a full hall', 'a speaker at a candlelit ceremony',
    ],
  },
  {
    name: 'family', upto: 32600, prompt: 'cinematic heartfelt photograph of ',
    tail: ', genuine love and warmth, soft natural light, shallow depth of field, sharp focus',
    mods: ['golden-hour glow', 'soft morning light', 'warm sunset backlight', 'cozy indoor light', 'bright airy daylight', 'candlelit warmth', 'dappled park light', 'gentle window light', 'sunny backyard light', 'warm hearth glow', 'beach afternoon light', 'autumn afternoon light'],
    scenes: [
      'a family laughing together in a sunny park', 'parents lifting a child at golden hour', 'three generations gathered at a dinner table', 'a family walking a beach at sunset', 'a mother and child reading together', 'a father teaching a child to fish', 'a family baking cookies in a warm kitchen', 'grandparents playing with grandchildren', 'a family cuddled on a couch under blankets', 'a family portrait in an autumn field',
      'a family decorating for the holidays', 'a family bike ride down a leafy street', 'parents and kids building a sandcastle', 'a family picnic under a big tree', 'a newborn held by loving parents', 'a family camping trip by a lake', 'a family playing in fall leaves', 'a family watching a sunrise together', 'a family gathered around a birthday cake', 'a family hug at an airport reunion',
    ],
  },
];
