const fs=require('fs');
const mk=(t,s)=>({title:t,slug:s});
const sl=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const cities=['Chicago','San Francisco','Atlanta','Houston','Dallas','Denver','Seattle','Boston','Philadelphia','San Diego','Scottsdale','Charlotte','Tampa','Orlando','Savannah','Memphis','Minneapolis','Portland, Oregon','Pittsburgh','Phoenix','Honolulu','Charleston','Kansas City','San Antonio','Fort Lauderdale','Key West','Annapolis, Maryland','Ocean City, Maryland','St. Louis','Cleveland'].map(c=>mk('Top 10 Nightlife Spots in '+c,'nightlife-'+sl(c)));
const intl=['London','Berlin','Amsterdam','Tokyo','Ibiza','Barcelona','Bangkok','Tulum','Mexico City','Toronto','Montreal','Dubai'].map(c=>mk('Top 10 Nightlife Spots in '+c,'nightlife-'+sl(c)));
const types=['Rooftop Bars in Miami','Rooftop Bars in Los Angeles','Rooftop Bars in Chicago','Speakeasies in New York City','Speakeasies in Chicago','Speakeasies in Los Angeles','Nightclubs in Miami','Nightclubs in Los Angeles','Nightclubs in Las Vegas','Dive Bars in New York City','Dive Bars in Chicago','Jazz Clubs in New Orleans','Jazz Clubs in New York City','Wine Bars in New York City','Wine Bars in San Francisco','Sports Bars in Chicago','Comedy Clubs in New York City','Comedy Clubs in Los Angeles','Gay Bars in New York City','Gay Bars in San Francisco','Tiki Bars in Los Angeles','Country Bars in Nashville','Cocktail Bars in New York City','Cocktail Bars in London','Beach Clubs in Miami','Rooftop Bars in Austin','Speakeasies in Washington, D.C.','Cocktail Bars in San Francisco','Live Music Venues in Austin','Nightclubs in Atlanta','Rooftop Bars in San Diego','Whiskey Bars in Nashville','Karaoke Bars in Los Angeles','Wine Bars in Chicago','Cocktail Bars in Chicago','Rooftop Bars in Washington, D.C.','Dive Bars in Austin','Comedy Clubs in Chicago','Nightclubs in San Diego','Speakeasies in Miami'].map(t=>mk('Top 10 '+t,sl(t)));
const all=[cities,types,intl];
const inter=[];let i=0,any=true;while(any){any=false;for(const p of all){if(i<p.length){inter.push(p[i]);any=true;}}i++;}
const out=inter.slice(0,100).map((e,k)=>({id:'nl'+String(11+k).padStart(4,'0'),title:e.title,slug:e.slug}));
fs.writeFileSync('C:/Users/koryj/_nl_sprint_queue.json',JSON.stringify(out,null,2));
console.log('nightlife queue:',out.length,'| first 6:',out.slice(0,6).map(e=>e.id+' '+e.title).join(' | '));
