const fs=require("fs");
const p="C:/Users/koryj/website/_scrub_button_server.js";
let s=fs.readFileSync(p,"utf8");
const a="  await syncGeneratedEntryMetadata(id, question, score, finalBody);\n  await queueNewEntryForScrubber(id, finalBody, { prepend: true, pipelineOrigin: 'generate' });\n  const factor1Pass = !!(result.passedGate || result.status === 'ready' || result.status === 'certified');";
const b="  await syncGeneratedEntryMetadata(id, question, score, finalBody);\n  const factor1Pass = !!(result.passedGate || result.status === 'ready' || result.status === 'certified');\n  const rubric13 = score >= 13 && factor1Pass;\n  if (result.status === 'certified' || rubric13) {\n    if (result.status !== 'certified') {\n      try {\n        await certify(id, 13, finalBody, { via: 'generate', rubric: result.rubric, title: question });\n        bumpDay();\n        genJob.published = (genJob.published || 0) + 1;\n      } catch (certErr) {\n        if (certErr && certErr.code === 'PUBLISH_IMAGE_GATE') {\n          await queueNewEntryForScrubber(id, finalBody, { prepend: true, pipelineOrigin: 'generate' });\n          setScrubStep('certify', 1, 1, 'Image gate — scrub queue');\n          markScrubStepDone('certify', 'Image gate → scrub queue');\n          touchScrubLive({ active: false, stage: 'idle', carwash: id + ' → scrub queue' });\n          return { status: 'queued', id, score, notes: certErr.message || 'image gate — queued for scrubber', factor1Pass: true, parked: true };\n        }\n        throw certErr;\n      }\n    } else {\n      genJob.published = (genJob.published || 0) + 1;\n    }\n    setScrubStep('certify', 1, 1, score + '/13 — published');\n    markScrubStepDone('certify', 'Certified ' + Math.min(13, score) + '/13');\n    touchScrubLive({ active: false, stage: 'idle', carwash: id + ' → live' });\n    genJob.stage = '✅ auto-indexed ' + score + '/13'; saveGen();\n    return { status: 'certified', id, score, notes: score + '/13 auto-certified', factor1Pass: true, parked: result.status === 'parked' };\n  }\n  await queueNewEntryForScrubber(id, finalBody, { prepend: true, pipelineOrigin: 'generate' });\n  const factor1PassAfterQueue = factor1Pass;";
if(!s.includes(a)){console.log("anchor missing");process.exit(1);} 
s=s.replace(a,b);
s=s.replace("  const factor1PassAfterQueue = factor1Pass;\n  setScrubStep('certify', 1, 1, factor1Pass ?","  setScrubStep('certify', 1, 1, factor1Pass ?");
fs.writeFileSync(p,s);
console.log("ok");
