// Follow-up email: the sitemap cap finding + fix + what to do after deploy.
const html = `
<div style="font-family:Arial,Helvetica,sans-serif;max-width:640px;margin:auto;color:#1a1a1a;line-height:1.5">
<h2 style="color:#E8710A;margin-bottom:4px">🗺️ Follow-up: why only ~10k pages showed up in your sitemap</h2>
<p style="margin-top:0;color:#555">Short version: a setting was capping the sitemap. Found it, fixed it. One thing needs to happen on your end.</p>

<h3 style="margin-bottom:4px">What was wrong</h3>
<p style="margin-top:0">Your library has <b>22,801</b> pages, but the sitemap generator had a hard cap that only output the <b>newest 5,000</b> (which Google counted as ~10,692 URLs). So roughly <b>17,000 of your pages were invisible</b> to Google. The other sitemaps are just naturally small — core pages (53), reviews (5,042), tools (32).</p>

<h3 style="margin-bottom:4px">The fix (done)</h3>
<p style="margin-top:0">I lifted the cap so the sitemap now includes <b>every</b> page. Once it's live, the knowledge sitemap jumps from ~10k to <b>~23k–30k URLs</b> — still safely under Google's limits.</p>

<h3 style="margin-bottom:4px">⚠️ What you need to do</h3>
<p style="margin-top:0">The sitemap is generated by a server function, so the fix only goes live after the <b>site is deployed</b> (you run the deploys). So:</p>
<ol style="margin-top:0;font-size:14px">
<li><b>Deploy the site</b> — the sitemap fix ships automatically with it. Nothing extra to configure.</li>
<li>After it's live, go to Search Console → <b>Sitemaps</b> → click the knowledge sitemap → <b>re-submit / refresh</b> (or just wait a day — Google re-reads it on its own). The "Discovered pages" count will climb from ~10k toward ~23k.</li>
</ol>

<h3 style="margin-bottom:4px">Meanwhile</h3>
<p style="margin-top:0;font-size:14px">Nothing is wasted — all the content is already live and the newest ~5k pages are being crawled right now. The deploy just makes Google aware of the rest. (Bing/Yandex already get everything via IndexNow.)</p>

<p style="color:#888;font-size:12px;margin-top:24px">Sent from your PULSE build assistant. The per-URL keyword-cluster backfill is still running across all 22,801 pages, and every future page gets its own cluster automatically.</p>
</div>`;

(async () => {
  const r = await fetch('https://pulserevops.com/.netlify/functions/pulse-progress-notify?key=pulsemachine-writer-2026', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ subject: '🗺️ Sitemap follow-up — fixed the 5k cap; one deploy needed to publish all 22k pages', html }),
    signal: AbortSignal.timeout(15000),
  });
  console.log('email POST status:', r.status, await r.text().catch(() => ''));
})().catch(e => { console.error('SEND ERR', e.message); process.exit(1); });
