const fs=require('fs');
const slug=s=>('best-towns-'+s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const mk=(t,s)=>({title:t,slug:s});
const states=['Virginia','Pennsylvania','North Carolina','Florida','Texas','California','Georgia','Ohio','Tennessee','Colorado','Arizona','Massachusetts','New York','New Jersey','Michigan','Washington','Oregon','South Carolina','Connecticut','Minnesota'].map(s=>mk('Top 10 Best Towns to Live in '+s,slug(s)));
const suburbs=['Washington, D.C.','New York City','Chicago','Boston','Philadelphia','Atlanta','Dallas','Denver','Seattle','Austin','Charlotte','Nashville','Raleigh','Phoenix','Minneapolis','Portland, Oregon','Tampa','Pittsburgh','Columbus','San Diego'].map(c=>mk('Top 10 Best Suburbs of '+c,('best-suburbs-'+c).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')));
const regional=['the American South','New England','the Pacific Northwest','the Midwest','the Mountain West','the Mid-Atlantic','the Southwest','the Gulf Coast'].map(r=>mk('Top 10 Best Towns to Live in '+r,slug(r)));
const cat=['Top 10 Best Small Towns in America|best-small-towns-america','Top 10 Best Beach Towns in America|best-beach-towns-america','Top 10 Best Mountain Towns in America|best-mountain-towns-america','Top 10 Best College Towns in America|best-college-towns-america','Top 10 Best Lake Towns in America|best-lake-towns-america','Top 10 Best Towns to Retire in America|best-retire-towns-america','Top 10 Best Affordable Towns to Live in America|best-affordable-towns-america','Top 10 Best Towns to Raise a Family in America|best-family-towns-america','Top 10 Safest Towns in America|safest-towns-america','Top 10 Best Walkable Small Towns in America|best-walkable-towns-america','Top 10 Best Wine Country Towns in America|best-wine-towns-america','Top 10 Best Ski Towns in America|best-ski-towns-america','Top 10 Best Historic Towns in America|best-historic-towns-america','Top 10 Best Towns for Remote Workers|best-remote-work-towns','Top 10 Best Towns to Live in on a Budget|best-budget-towns','Top 10 Best Up-and-Coming Towns in America|best-upcoming-towns','Top 10 Best Coastal Towns in America|best-coastal-towns-america','Top 10 Best River Towns in America|best-river-towns-america'].map(s=>{const[t,sl]=s.split('|');return mk(t,sl);});
const national=['Top 10 Best Towns to Live in America|best-towns-america','Top 10 Best Places to Live in the United States|best-places-usa'].map(s=>{const[t,sl]=s.split('|');return mk(t,sl);});
const all=[states,suburbs,regional,cat,national];
const inter=[];let i=0,any=true;while(any){any=false;for(const p of all){if(i<p.length){inter.push(p[i]);any=true;}}i++;}
const out=inter.slice(0,100).map((e,k)=>({id:'tn'+String(11+k).padStart(4,'0'),title:e.title,slug:e.slug}));
fs.writeFileSync('C:/Users/koryj/_tn_sprint_queue.json',JSON.stringify(out,null,2));
console.log('towns queue:',out.length,'| first 6:',out.slice(0,6).map(e=>e.id+' '+e.title).join(' | '));
