// ─────────────────────────────────────────────────────────────────────────
// PULSE per-pillar TWO-TONE palette — the ONE source of truth for pillar color.
// Each pillar has a UNIQUE [primary, secondary]. Primary = logo line-art +
// "Pulse" wordmark + answer-page accent (links, labels, eyebrow). Secondary =
// the second half of the diagonal stripe inside the logo (e.g. Events = pink +
// black, AI = blue + black). Background stays the parchment #EBE9DE patterned
// backdrop. User-specified vibes: events=pink/black, ai=blue/black.
//
// BY_LOGO_KEY is keyed by the logo filename key (pulse-<key>-logo.svg), used by
// gen-pillars.js + the standalone recolor pass.
// BY_PREFIX is keyed by entry-id prefix, used by the answer-page renderer.
// ─────────────────────────────────────────────────────────────────────────

const BY_LOGO_KEY = {
  // ── generated by gen-pillars.js (I{} map) ──
  knowledge:            ['#C0531F', '#2A1206'],
  revenue:              ['#1B7A3D', '#0A3019'],
  gtm:                  ['#1C6EA4', '#082635'],
  kpi:                  ['#1565C0', '#071E3C'],
  tech:                 ['#3B5BA5', '#101A33'],
  events:               ['#EC2D7C', '#141414'], // user: pink + black
  nightlife:            ['#7A1FA2', '#1C0A28'],
  gaming:               ['#6D28D9', '#170A33'],
  skills:               ['#3949AB', '#0D1234'],
  speeches:             ['#8E1B4B', '#260711'],
  boats:                ['#0E6BA8', '#052433'],
  travel:               ['#1C9AD6', '#063347'],
  resorts:              ['#0E9C9C', '#04302F'],
  aquariums:            ['#0E7C86', '#03282B'],
  gatherings:           ['#C026D3', '#260A2A'],
  cars:                 ['#C0392B', '#2A0907'],
  franchises:           ['#1E3A5F', '#C8972E'],
  movies:               ['#B71C3B', '#270710'],
  reviews:              ['#E08A1E', '#3A2206'],
  estates:              ['#B8860B', '#2C1F03'],
  clubs:                ['#2E7D32', '#0B280D'],
  'football-recruiting':['#B45309', '#2C1403'],
  wellness:             ['#2E9E5B', '#0C321F'],
  living:               ['#A0522D', '#28130A'],
  style:                ['#BE185D', '#260512'],
  graphics:             ['#0D9488', '#04302B'],
  books:                ['#8B5A2B', '#241405'],
  towns:                ['#5B7553', '#182015'],
  drills:               ['#D2691E', '#341805'],
  pets:                 ['#0E8C7A', '#042E28'],
  software:             ['#475569', '#131A24'],
  // ── standalone SVGs (recolored from the #C0531F template) ──
  ai:                   ['#0A66C2', '#0A0A0A'], // user: blue + black
  coaching:             ['#0891B2', '#04303A'],
  collectibles:         ['#92400E', '#2A1304'],
  sports:               ['#166534', '#06250F'],
  tools:                ['#52525B', '#18181B'],
  dining:               ['#9F1239', '#270710'],
  schools:              ['#1E40AF', '#0A1533'],
  trainings:            ['#2563EB', '#0A1A3A'],
  buildouts:            ['#D97706', '#341B03'],
};

// Entry-id prefix → logo key (so the renderer maps pt0001 → pets palette, etc.)
const PREFIX_TO_KEY = {
  q:'knowledge', ra:'revenue', gp:'gtm', ik:'kpi', tk:'tech', ev:'events',
  nl:'nightlife', gm:'gaming', sk:'skills', sp:'speeches', bt:'boats',
  tv:'travel', rs:'resorts', aq:'aquariums', ga:'gatherings', ca:'cars',
  fr:'franchises', mv:'movies', er:'reviews', es:'estates', cl:'clubs',
  hf:'football-recruiting', wl:'wellness', lv:'living', sy:'style',
  gb:'graphics', bs:'books', tn:'towns', dr:'drills', pt:'pets', sw:'software',
  ai:'ai', cg:'coaching', co:'collectibles', tl:'tools', dn:'dining',
  sc:'schools', st:'trainings', bo:'buildouts',
};

const BY_PREFIX = {};
for (const p in PREFIX_TO_KEY) { BY_PREFIX[p] = BY_LOGO_KEY[PREFIX_TO_KEY[p]]; }

module.exports = { BY_LOGO_KEY, BY_PREFIX, PREFIX_TO_KEY };
