// Canonical Pulse News brand assets for favicon, social share, PWA, and Google SERP logo.
// Black Pulse News badge on dark square — generated by _gen_pulse_news_brand.js.
// NO lightbulb assets — use these paths everywhere.

const PULSE_SITE = 'https://pulserevops.com';
const PULSE_ORG_LOGO_PATH = '/icon-512.png';
const PULSE_ORG_LOGO_URL = PULSE_SITE + PULSE_ORG_LOGO_PATH;
const PULSE_ORG_ID = PULSE_SITE + '/#organization';
const PULSE_FAVICON_ICO = '/favicon.ico';
const PULSE_ICON_192 = '/icon-192.png';
const PULSE_ICON_512 = '/icon-512.png';
const PULSE_APPLE_TOUCH = '/apple-touch-icon.png';
const PULSE_SHARE_ICON = '/icon-192.png';
const PULSE_OG_IMAGE = '/pulse-og.png';

function pulseOrgLogoImageObject() {
  return {
    '@type': 'ImageObject',
    url: PULSE_ORG_LOGO_URL,
    width: 512,
    height: 512,
    caption: 'Pulse News logo',
  };
}

/** Minimal Organization node with logo — merge extra fields as needed. */
function pulseOrganizationStub(extra = {}) {
  return {
    '@type': 'Organization',
    '@id': PULSE_ORG_ID,
    name: 'Pulse News',
    url: PULSE_SITE,
    logo: pulseOrgLogoImageObject(),
    ...extra,
  };
}

module.exports = {
  PULSE_SITE,
  PULSE_ORG_LOGO_PATH,
  PULSE_ORG_LOGO_URL,
  PULSE_ORG_ID,
  PULSE_FAVICON_ICO,
  PULSE_ICON_192,
  PULSE_ICON_512,
  PULSE_APPLE_TOUCH,
  PULSE_SHARE_ICON,
  PULSE_OG_IMAGE,
  pulseOrgLogoImageObject,
  pulseOrganizationStub,
};
