const fs = require('fs');
const t = fs.readFileSync('_gold_q2138_solo.md', 'utf8');
const words = t.trim().split(/\s+/).length;
console.log('1. words=', words);
console.log('2. directAnswer=', (t.match(/### Direct Answer/g) || []).length);
console.log('3. tldr=', (t.match(/TL;DR/g) || []).length);
console.log('4. h2 banners=', (t.match(/\n## /g) || []).length);
const subs = [...t.matchAll(/\n### (\d+)\.(\d+) /g)].map(m => m[1] + '.' + m[2]);
console.log('5. numbered subsections=', subs.length, subs.join(' '));
console.log('6. bold-lead bullets=', (t.match(/\n- \*\*/g) || []).length);
const fence = String.fromCharCode(96, 96, 96);
console.log('7. mermaid blocks=', (t.match(new RegExp(fence + 'mermaid', 'g')) || []).length);
console.log('8. table separator rows=', (t.match(/\|---/g) || []).length, ' tables=', (t.match(/### Table \d+/g) || []).length);
console.log('9. counterCase=', (t.match(/Counter-Case/g) || []).length);
const cl = [...new Set((t.match(/\(q\d+\)/g) || []))];
console.log('10. crosslinks=', cl.length, cl.join(' '));
const cites = (t.match(/\n\d+\. /g) || []).length;
console.log('   citations=', cites);
console.log('   wiki-bracket links (must be 0)=', (t.match(/\[\[q\d+\]\]/g) || []).length);
