const fs = require('fs');
const t = fs.readFileSync('C:/Users/koryj/website/lab/_gold_q466_solo.md', 'utf8');
const wc = t.trim().split(/\s+/).length;
console.log('WORD COUNT:', wc);
console.log('--- ELEMENT CHECKS ---');
console.log('1 Direct Answer H3:', /^### Direct Answer/m.test(t));
console.log('2 TLDR block:', /\*\*TLDR\*\*/.test(t));
console.log('3 H2 banners:', (t.match(/^## /gm) || []).length);
const subs = (t.match(/^### \d+\.\d+ /gm) || []).map(s => s.match(/\d+\.\d+/)[0]);
console.log('4 numbered subsections:', subs.join(' '));
console.log('5 bold-lead bullets:', (t.match(/^- \*\*/gm) || []).length);
console.log('6 ticker (CRM):', /\(CRM\)/.test(t));
console.log('7 mermaid blocks:', (t.match(/```mermaid/g) || []).length);
console.log('8 pipe tables:', (t.match(/^\|---/gm) || []).length);
console.log('9 Counter-Case section:', /Counter-Case/.test(t));
const links = [...new Set((t.match(/\(q\d+\)/g) || []))];
console.log('10 cross-links:', links.join(' '), 'count=' + links.length);
console.log('wiki brackets (should be false):', /\[\[q\d+\]\]/.test(t));
console.log('citations:', (t.match(/^\d+\. /gm) || []).length);
