const fs = require('fs');
const md = fs.readFileSync('C:/Users/koryj/website/lab/_gold_q2153_s1b.md', 'utf8');
const words = md.trim().split(/\s+/).length;
const directAnswer = /^### Direct Answer/m.test(md);
const tldr = /\*\*TL;DR\*\*/.test(md);
const h2 = (md.match(/^## /gm) || []).length;
const subs = (md.match(/^### \d+\.\d+/gm) || []).map(s => s.replace('### ', '').trim());
const tables = (md.match(/^\|.*\|.*\|/gm) || []).filter(l => !/^\|[\s:|-]+\|$/.test(l));
const tableHeaderRows = (md.match(/^\|[\s:|-]+\|$/gm) || []).length;
const mermaid = (md.match(/```mermaid/g) || []).length;
const crosslinks = [...md.matchAll(/\(q\d+\)/g)].map(m => m[0]);
const wikilinks = (md.match(/\[\[q\d+\]\]/g) || []).length;
const sources = (md.match(/^\d+\. /gm) || []).length;
const counterCase = /## Counter-Case/.test(md);
let out = '';
out += 'WORD COUNT: ' + words + '\n';
out += '1. Direct Answer H3: ' + directAnswer + '\n';
out += '2. TL;DR block: ' + tldr + '\n';
out += '3. H2 banners: ' + h2 + '\n';
out += '4. Numbered subsections: ' + subs.join(', ') + '\n';
out += '5. Bold-lead present: ' + /\*\*[A-Z]/.test(md) + '\n';
out += '6. Tickers present: ' + (/NYSE:|NASDAQ:|NASDAQ American|NYSE American|STO:/.test(md)) + '\n';
out += '7. Mermaid blocks: ' + mermaid + '\n';
out += '8. Pipe table header rows (separators): ' + tableHeaderRows + '\n';
out += '9. Counter-Case section: ' + counterCase + '\n';
out += '10. Cross-links (q####): ' + crosslinks.length + ' -> ' + [...new Set(crosslinks)].join(', ') + '\n';
out += '   Wiki [[q]] brackets (should be 0): ' + wikilinks + '\n';
out += '   Numbered citations: ' + sources + '\n';
fs.writeFileSync('C:/Users/koryj/website/lab/_verify_out.txt', out);
